import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { WorkspacePageHeader, WorkspaceSection, WorkspaceState } from "@/components/workspace/WorkspacePrimitives";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Copy, FileUp, Landmark } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const allowed = ["image/jpeg", "image/png", "image/webp", "application/pdf"];
const money = (value: number | null | undefined) => value == null ? "—" : new Intl.NumberFormat("ka-GE", { style: "currency", currency: "GEL" }).format(value / 100);

export default function BillingActivation() {
  const { user } = useAuth(); const orgs = trpc.organizations.listMine.useQuery(); const entry = orgs.data?.[0]; const owner = entry?.membership.role === "OWNER"; const status = trpc.billing.ownerStatus.useQuery({ organizationId: entry?.organization.id ?? "" }, { enabled: Boolean(owner && entry?.organization.id) });
  const utils = trpc.useUtils(); const [comment, setComment] = useState(""); const [file, setFile] = useState<File | null>(null);
  const submit = trpc.billing.submitReceipt.useMutation({ onSuccess: async () => { await utils.billing.ownerStatus.invalidate(); setFile(null); toast.success("ქვითარი გაიგზავნა ხელით შესამოწმებლად."); }, onError: e => toast.error(e.message) });
  const copy = async (text: string) => { await navigator.clipboard.writeText(text); toast.success("დაკოპირებულია."); };
  const send = async () => { if (!file || !entry) return toast.error("ატვირთეთ ქვითარი JPG, PNG, WEBP ან PDF ფორმატში."); if (!allowed.includes(file.type) || file.size > 10 * 1024 * 1024) return toast.error("ფაილი უნდა იყოს JPG, PNG, WEBP ან PDF და მაქსიმუმ 10 MB."); const dataUrl = await new Promise<string>((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve(String(r.result)); r.onerror = reject; r.readAsDataURL(file); }); submit.mutate({ organizationId: entry.organization.id, transferComment: comment || `${status.data?.config?.transferCommentPrefix ?? "SF"}-${status.data?.organization.billingCode ?? ""}`, originalName: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "image/webp" | "application/pdf", dataUrl }); };
  if (!user || orgs.isLoading) return <DashboardLayout><WorkspaceState kind="loading" title="გადახდის ინფორმაცია იტვირთება…" /></DashboardLayout>;
  if (!owner) return <DashboardLayout><WorkspaceState kind="empty" title="წვდომა დასრულებულია" description="აქტივაციის ქვითრის ატვირთვა შეუძლია მხოლოდ სალონის მფლობელს." /></DashboardLayout>;
  const c = status.data?.config; const suggested = `${c?.transferCommentPrefix ?? "SF"}-${status.data?.organization.billingCode ?? ""}`;
  return <DashboardLayout><main className="sf-workspace-page mx-auto w-full max-w-4xl space-y-5"><WorkspacePageHeader eyebrow="MANUAL BANK TRANSFER" title="1-თვიანი პაკეტის გააქტიურება" description="გადარიცხვის შემდეგ მიუთითეთ სალონის ID კომენტარში და ატვირთეთ ქვითარი ხელით შესამოწმებლად." />{status.isLoading ? <WorkspaceState kind="loading" title="ინსტრუქცია იტვირთება…" /> : null}{!c ? <WorkspaceState kind="empty" title="გადახდის რეკვიზიტები ჯერ არ არის კონფიგურირებული" description="Platform admin-მა ჯერ უნდა შეავსოს ბენეფიციარისა და 1-თვიანი პაკეტის ინფორმაცია." /> : <><WorkspaceSection title="გადარიცხვის დეტალები" description="ეს მონაცემები გამოიყენეთ საბანკო გადარიცხვისას."><div className="grid gap-3 sm:grid-cols-2">{[["ბენეფიციარი", c.beneficiaryName], ["პირადი ნომერი", c.personalNumber], ["ანგარიშის ნომერი", c.accountNumber], ["1-თვიანი პაკეტი", money(c.monthlyPriceTetri)]].map(([label, value]) => <div key={label} className="rounded-2xl border bg-muted/10 p-4"><p className="text-xs text-muted-foreground">{label}</p><div className="mt-2 flex items-center justify-between gap-2"><strong className="break-all text-sm">{value}</strong>{value && label !== "1-თვიანი პაკეტი" ? <Button size="icon" variant="ghost" aria-label={`${label} დაკოპირება`} onClick={() => copy(value)}><Copy className="size-4" /></Button> : null}</div></div>)}</div></WorkspaceSection><WorkspaceSection title="სალონის ID და ქვითარი" description="ეს ID მიუთითეთ გადარიცხვის კომენტარში, რათა admin-მა გადახდა სწორ სალონს დააკავშიროს."><div className="space-y-4"><div className="rounded-2xl border border-primary/30 bg-primary/5 p-4"><p className="text-xs text-muted-foreground">თქვენი სალონის ID / გადარიცხვის კომენტარი</p><div className="mt-2 flex items-center justify-between gap-3"><strong className="font-mono">{suggested}</strong><Button size="sm" variant="outline" onClick={() => copy(suggested)}>დაკოპირება</Button></div></div><Input value={comment} onChange={e => setComment(e.target.value)} placeholder={suggested} aria-label="გადარიცხვის კომენტარი" maxLength={160} /><Input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e => setFile(e.target.files?.[0] ?? null)} aria-label="ქვითრის ატვირთვა" /><p className="text-xs text-muted-foreground">JPEG, PNG, WEBP ან PDF · მაქსიმუმ 10 MB · ქვითარი ხელით შემოწმდება.</p><Button onClick={send} disabled={submit.isPending || !file}><FileUp className="mr-2 size-4" />{submit.isPending ? "იგზავნება…" : "ქვითრის გაგზავნა"}</Button>{status.data?.submission ? <p role="status" className="text-sm text-muted-foreground">ბოლო ქვითრის სტატუსი: <strong>{status.data.submission.status}</strong></p> : null}</div></WorkspaceSection></>}</main></DashboardLayout>;
}
