import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { WorkspacePageHeader, WorkspaceSection, WorkspaceState } from "@/components/workspace/WorkspacePrimitives";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function BillingAdmin() {
  const { user, loading } = useAuth(); const [, go] = useLocation(); const utils = trpc.useUtils(); const config = trpc.billing.adminConfig.useQuery(undefined, { enabled: user?.role === "admin" });
  const [form, setForm] = useState({ beneficiaryName: "", personalNumber: "", accountNumber: "", monthlyPriceTetri: "", transferCommentPrefix: "SF", privacyNoticeKa: "ქვითარი ხელით მოწმდება SalonFlow platform admin-ის მიერ." }); const [search, setSearch] = useState(""); const list = trpc.billing.adminList.useQuery({ search: search || undefined }, { enabled: user?.role === "admin" });
  const save = trpc.billing.saveConfig.useMutation({ onSuccess: async () => { await utils.billing.adminConfig.invalidate(); toast.success("რეკვიზიტები შენახულია."); }, onError: e => toast.error(e.message) }); const approve = trpc.billing.approveMonthly.useMutation({ onSuccess: async result => { await utils.billing.adminList.invalidate(); toast.success(`1-თვიანი წვდომა გააქტიურდა ${new Date(result.endsAt).toLocaleDateString("ka-GE")}-მდე.`); }, onError: e => toast.error(e.message) });
  useEffect(() => { if (!loading && user && user.role !== "admin") go("/app/today"); }, [go, loading, user]);
  if (!loading && user && user.role !== "admin") return <DashboardLayout><WorkspaceState kind="loading" title="თქვენს სამუშაო სივრცეში გადამისამართება…" /></DashboardLayout>;
  if (loading || !user) return <DashboardLayout><WorkspaceState kind="loading" title="წვდომა მოწმდება…" /></DashboardLayout>;
  const c = config.data; const value = (key: keyof typeof form) => form[key] || (key === "monthlyPriceTetri" ? String(c?.monthlyPriceTetri ?? "") : String(c?.[key as keyof NonNullable<typeof c>] ?? ""));
  return <DashboardLayout><main className="sf-workspace-page mx-auto w-full max-w-6xl space-y-5"><WorkspacePageHeader eyebrow="PLATFORM ADMIN" title="Billing payments" description="ხელით საბანკო გადარიცხვის რეკვიზიტები და ქვითრების შემოწმება." /><WorkspaceSection title="გადახდის რეკვიზიტები" description="ეს მონაცემები გამოჩნდება მხოლოდ ვადაგასული workspace-ის მფლობელთან."><div className="grid gap-3 md:grid-cols-2">{([['beneficiaryName','ბენეფიციარის სახელი'],['personalNumber','პირადი ნომერი'],['accountNumber','ანგარიშის ნომერი'],['monthlyPriceTetri','ფასი tetri-ში'],['transferCommentPrefix','კომენტარის prefix'],['privacyNoticeKa','Privacy ტექსტი']] as const).map(([key,label]) => <label key={key} className="grid gap-1 text-sm"><span>{label}</span><Input value={value(key)} onChange={e => setForm(x => ({ ...x, [key]: e.target.value }))} /></label>)}</div><Button className="mt-4" onClick={() => save.mutate({ beneficiaryName: value('beneficiaryName'), personalNumber: value('personalNumber'), accountNumber: value('accountNumber'), monthlyPriceTetri: Number(value('monthlyPriceTetri')), transferCommentPrefix: value('transferCommentPrefix'), privacyNoticeKa: value('privacyNoticeKa') })} disabled={save.isPending}>შენახვა</Button></WorkspaceSection><WorkspaceSection title="ქვითრები" description="დაადასტურეთ მხოლოდ ხელით შემოწმებული ქვითარი."><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="სალონის სახელი, ID ან მფლობელის ელფოსტა" /><div className="mt-4 grid gap-3">{list.data?.map(item => <article key={item.id} className="rounded-2xl border p-4"><p className="font-semibold">{item.organizationName} · {item.billingCodeSnapshot}</p><p className="mt-1 text-sm text-muted-foreground">{item.ownerEmail} · {item.status} · {item.transferComment}</p><div className="mt-3 flex gap-2"><Button asChild size="sm" variant="outline"><a href={item.receiptUrl} target="_blank" rel="noreferrer">ქვითრის ნახვა</a></Button>{['SUBMITTED','UNDER_REVIEW'].includes(item.status) ? <Button size="sm" onClick={() => approve.mutate({ submissionId: item.id })}>1 თვე</Button> : null}</div></article>)}{!list.isLoading && !list.data?.length ? <WorkspaceState kind="empty" title="ქვითარი არ არის" /> : null}</div></WorkspaceSection></main></DashboardLayout>;
}
