import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CalendarDays, ChevronLeft, MapPin } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

export default function Book() {
  const locations = trpc.public.locations.useQuery();
  return <main className="min-h-screen bg-[#F7F4EF] px-5 py-8 text-[#1E2824] sm:px-8"><div className="mx-auto max-w-xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-medium text-[#516159]"><ChevronLeft className="h-4 w-4" /> მთავარ გვერდზე</Link><header className="mt-12"><p className="text-sm font-semibold text-[#B85C3D]">ონლაინ ჩაწერა</p><h1 className="mt-3 font-serif text-4xl font-semibold tracking-tight">აირჩიეთ ფილიალი</h1><p className="mt-3 text-sm leading-6 text-[#617068]">შემდეგ აირჩევთ სერვისს, სპეციალისტს, დროს და საკონტაქტო ინფორმაციას.</p></header>{locations.isLoading ? <div className="mt-8 rounded-2xl border bg-white p-6 text-sm text-muted-foreground">ფილიალები იტვირთება…</div> : null}{locations.isError ? <div className="mt-8 rounded-2xl border border-destructive/30 bg-destructive/5 p-6 text-sm text-destructive">ონლაინ ჩაწერის მონაცემები დროებით მიუწვდომელია.</div> : null}{locations.data?.length === 0 ? <Card className="mt-8 border-[#1E2824]/10"><CardHeader><CalendarDays className="h-5 w-5 text-[#B85C3D]" /><CardTitle className="mt-4">ჩაწერა მალე გააქტიურდება</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-muted-foreground">სალონს ჯერ არ აქვს აქტიური ონლაინ-ჩაწერის ფილიალი. გთხოვთ დაუკავშირდეთ სალონს უშუალოდ.</CardContent></Card> : null}<div className="mt-8 space-y-3">{locations.data?.map(location => <Card key={location.publicSlug} className="border-[#1E2824]/10"><CardContent className="flex items-center justify-between gap-4 p-5"><div><p className="font-semibold">{location.name}</p>{location.address ? <p className="mt-2 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="h-4 w-4" />{location.address}</p> : null}</div><Button asChild className="bg-[#B85C3D] hover:bg-[#9D4C31]"><Link href={`/book/${location.publicSlug}`}>არჩევა</Link></Button></CardContent></Card>)}</div></div></main>;
}
