import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, UsersRound } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useMemo, useState } from "react";

const statusLabels: Record<string, string> = { PENDING: "დადასტურებას ელოდება", CONFIRMED: "დადასტურებული", CHECKED_IN: "მოსულია", IN_SERVICE: "მომსახურებაშია", COMPLETED: "დასრულებული", CANCELLED: "გაუქმებული", NO_SHOW: "არ გამოცხადდა" };
const statusTone: Record<string, string> = { PENDING: "border-[#D69A43]/30 bg-[#D69A43]/10 text-[#855B12]", CONFIRMED: "border-[#17826A]/30 bg-[#17826A]/10 text-[#216451]", CHECKED_IN: "border-[#17826A]/30 bg-[#17826A]/10 text-[#216451]", IN_SERVICE: "border-primary/30 bg-primary/10 text-primary", COMPLETED: "border-[#516159]/20 bg-[#516159]/10 text-[#516159]", CANCELLED: "border-destructive/30 bg-destructive/10 text-destructive", NO_SHOW: "border-destructive/30 bg-destructive/10 text-destructive" };

function startOfWeek(value: Date) { const date = new Date(value); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date; }
function addDays(value: Date, days: number) { const date = new Date(value); date.setDate(date.getDate() + days); return date; }
function sameDay(left: Date, right: Date) { return left.getFullYear() === right.getFullYear() && left.getMonth() === right.getMonth() && left.getDate() === right.getDate(); }
function time(value: Date) { return new Intl.DateTimeFormat("ka-GE", { hour: "2-digit", minute: "2-digit" }).format(value); }

export default function Calendar() {
  const organizations = trpc.organizations.listMine.useQuery();
  const organizationEntry = organizations.data?.[0];
  const organization = organizationEntry?.organization;
  const isStaff = organizationEntry?.membership.role === "STAFF";
  const [view, setView] = useState<"day" | "week">("week");
  const [cursor, setCursor] = useState(() => startOfWeek(new Date()));
  const [staffFilter, setStaffFilter] = useState("ALL");
  const range = useMemo(() => { const startsAt = new Date(cursor); const endsAt = addDays(startsAt, view === "week" ? 7 : 1); return { startsAt, endsAt }; }, [cursor, view]);
  const calendarInput = useMemo(() => ({ organizationId: organization?.id ?? "", ...range, staffProfileId: staffFilter === "ALL" ? undefined : staffFilter }), [organization?.id, range, staffFilter]);
  const appointments = trpc.appointments.listRange.useQuery(calendarInput, { enabled: Boolean(organization?.id) });
  const staff = trpc.staff.list.useQuery({ organizationId: organization?.id ?? "" }, { enabled: Boolean(organization?.id) && !isStaff });
  const days = useMemo(() => Array.from({ length: view === "week" ? 7 : 1 }, (_, index) => addDays(cursor, index)), [cursor, view]);
  const periodLabel = view === "week" ? `${new Intl.DateTimeFormat("ka-GE", { day: "numeric", month: "long" }).format(days[0])} – ${new Intl.DateTimeFormat("ka-GE", { day: "numeric", month: "long", year: "numeric" }).format(days[6])}` : new Intl.DateTimeFormat("ka-GE", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(cursor);
  const move = (direction: -1 | 1) => setCursor(current => addDays(current, direction * (view === "week" ? 7 : 1)));
  const switchView = (next: "day" | "week") => { setView(next); setCursor(current => next === "week" ? startOfWeek(current) : current); };

  return <DashboardLayout><div className="mx-auto w-full max-w-7xl space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium text-primary">გუნდის ოპერაციები</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">კალენდარი</h1><p className="mt-2 text-sm text-muted-foreground">{periodLabel} · დაგეგმილი ჯავშნები სპეციალისტების მიხედვით.</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="w-fit border-primary/30 bg-primary/5 px-3 py-1 text-primary">{organization?.name ?? "სამუშაო სივრცე"}</Badge><div className="flex rounded-lg border p-1"><Button variant={view === "day" ? "default" : "ghost"} size="sm" onClick={() => switchView("day")}>დღე</Button><Button variant={view === "week" ? "default" : "ghost"} size="sm" onClick={() => switchView("week")}>კვირა</Button></div></div></header>
    {organizations.isLoading ? <CalendarState text="სამუშაო სივრცე იტვირთება…" /> : null}{organizations.isError ? <CalendarState error text="სამუშაო სივრცის მონაცემები დროებით მიუწვდომელია." /> : null}{!organizations.isLoading && !organizations.isError && !organization ? <CalendarState text="კალენდრის სანახავად ჯერ შექმენით თქვენი პირველი სამუშაო სივრცე." /> : null}
    {organization ? <><Card><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><Button variant="outline" size="icon" onClick={() => move(-1)} aria-label="წინა პერიოდი"><ChevronLeft className="h-4 w-4" /></Button><p className="min-w-52 text-center text-sm font-medium">{periodLabel}</p><Button variant="outline" size="icon" onClick={() => move(1)} aria-label="შემდეგი პერიოდი"><ChevronRight className="h-4 w-4" /></Button></div>{!isStaff ? <Select value={staffFilter} onValueChange={setStaffFilter}><SelectTrigger className="w-full sm:w-64"><SelectValue placeholder="ყველა სპეციალისტი" /></SelectTrigger><SelectContent><SelectItem value="ALL">ყველა სპეციალისტი</SelectItem>{staff.data?.map(item => <SelectItem key={item.profile.id} value={item.profile.id}>{item.profile.publicDisplayName}</SelectItem>)}</SelectContent></Select> : <p className="text-sm text-muted-foreground">ნაჩვენებია მხოლოდ თქვენი განრიგი.</p>}</CardContent></Card>
      <div className="grid gap-4 lg:grid-cols-[0.7fr_2.3fr]"><Card className="h-fit"><CardHeader><CalendarDays className="h-5 w-5 text-primary" /><CardTitle className="mt-3">პერიოდის მიმოხილვა</CardTitle></CardHeader><CardContent className="space-y-4"><div><p className="text-3xl font-semibold">{appointments.isLoading ? "…" : appointments.data?.length ?? 0}</p><p className="mt-1 text-sm text-muted-foreground">სულ ჯავშანი</p></div><div className="rounded-xl bg-primary/5 p-4 text-sm leading-6 text-muted-foreground"><UsersRound className="mb-2 h-4 w-4 text-primary" />სპეციალისტის ფილტრი და პერიოდის ხედვა სრულდება სერვერზე შემოწმებული ორგანიზაციის წვდომით.</div></CardContent></Card><Card><CardHeader><div className="flex items-center justify-between"><CardTitle>{view === "week" ? "კვირის განრიგი" : "დღის განრიგი"}</CardTitle><Clock3 className="h-5 w-5 text-primary" /></div></CardHeader><CardContent>{appointments.isLoading ? <p className="py-8 text-center text-sm text-muted-foreground">ჯავშნები იტვირთება…</p> : null}{appointments.isError ? <p className="py-8 text-center text-sm text-destructive">ჯავშნების ჩატვირთვა ვერ მოხერხდა.</p> : null}{!appointments.isLoading && !appointments.isError && appointments.data?.length === 0 ? <p className="rounded-xl border border-dashed p-8 text-center text-sm leading-6 text-muted-foreground">ამ პერიოდში ჯავშნები ჯერ არ არის. ახალი საჯარო ან შიდა ჩაწერა აქ ავტომატურად გამოჩნდება.</p> : null}{!appointments.isLoading && !appointments.isError && appointments.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-7">{days.map(day => { const dayAppointments = appointments.data.filter(appointment => sameDay(new Date(appointment.startsAt), day)); return <section key={day.toISOString()} className="min-w-0 rounded-xl border bg-card/50 p-3"><header className="border-b pb-2"><p className="text-xs font-medium uppercase tracking-wide text-primary">{new Intl.DateTimeFormat("ka-GE", { weekday: "short" }).format(day)}</p><p className="mt-1 font-semibold">{new Intl.DateTimeFormat("ka-GE", { day: "numeric", month: "short" }).format(day)}</p></header><div className="mt-3 space-y-2">{dayAppointments.length ? dayAppointments.map(appointment => <div key={appointment.id} className="rounded-lg border bg-background p-3"><p className="text-sm font-semibold">{time(appointment.startsAt)} – {time(appointment.endsAt)}</p><p className="mt-1 truncate font-mono text-[11px] text-muted-foreground">#{appointment.id.slice(-8).toUpperCase()}</p><Badge variant="outline" className={`mt-2 text-[11px] ${statusTone[appointment.status] ?? ""}`}>{statusLabels[appointment.status] ?? appointment.status}</Badge></div>) : <p className="py-4 text-center text-xs text-muted-foreground">თავისუფალია</p>}</div></section>; })}</div> : null}</CardContent></Card></div></> : null}
  </div></DashboardLayout>;
}

function CalendarState({ text, error = false }: { text: string; error?: boolean }) { return <Card className={error ? "border-destructive/30 bg-destructive/5" : ""}><CardContent className={`p-8 text-sm ${error ? "text-destructive" : "text-muted-foreground"}`}>{text}</CardContent></Card>; }
