import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, MapPin, UsersRound } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { DragEvent, useEffect, useMemo, useState } from "react";
import { dateKeyInTimeZone, formatTimeInTimeZone, zonedDateTimeToUtc } from "@shared/timezones";
import { toast } from "sonner";
import { canManageAppointmentQueue, nextAppointmentAction } from "@/lib/appointmentPresentation";
import { AppointmentQuickAction } from "@/components/AppointmentQuickAction";
import { WorkspaceFilterBar, WorkspacePageHeader, WorkspaceSection, WorkspaceState, WorkspaceStatusPill } from "@/components/workspace/WorkspacePrimitives";
import { formatPaymentState } from "@/lib/presentation";

const statusLabels: Record<string, string> = { PENDING: "დასადასტურებელი", CONFIRMED: "დადასტურებული", CHECKED_IN: "მიღებულია", IN_SERVICE: "მომსახურებაშია", COMPLETED: "დასრულებული", CANCELLED: "გაუქმებული", NO_SHOW: "არ გამოცხადდა" };
const statusTone: Record<string, string> = { PENDING: "border-[var(--sf-amber)]/35 bg-[var(--sf-amber)]/15 text-[var(--sf-amber)]", CONFIRMED: "border-[var(--sf-jade)]/30 bg-[var(--sf-jade)]/10 text-[var(--sf-jade)]", CHECKED_IN: "border-[var(--sf-jade)]/30 bg-[var(--sf-jade)]/10 text-[var(--sf-jade)]", IN_SERVICE: "border-primary/30 bg-primary/10 text-primary", COMPLETED: "border-[var(--sf-muted)]/20 bg-[var(--sf-muted)]/10 text-[var(--sf-muted)]", CANCELLED: "border-destructive/30 bg-destructive/10 text-destructive", NO_SHOW: "border-destructive/30 bg-destructive/10 text-destructive" };
const FIRST_HOUR = 8;
const LAST_HOUR = 21;
const PIXELS_PER_MINUTE = 1;
const hours = Array.from({ length: LAST_HOUR - FIRST_HOUR }, (_, index) => FIRST_HOUR + index);

function startOfWeek(value: Date) { const date = new Date(Date.UTC(value.getUTCFullYear(), value.getUTCMonth(), value.getUTCDate())); date.setUTCDate(date.getUTCDate() - ((date.getUTCDay() + 6) % 7)); return date; }
function addDays(value: Date, days: number) { const date = new Date(Date.UTC(value.getUTCFullYear(), value.getUTCMonth(), value.getUTCDate())); date.setUTCDate(date.getUTCDate() + days); return date; }
function dayStart(value: Date, timezone: string) { return zonedDateTimeToUtc({ year: value.getUTCFullYear(), month: value.getUTCMonth() + 1, day: value.getUTCDate(), hour: 0, minute: 0, second: 0 }, timezone); }
function minuteOfDay(value: Date, timezone: string) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: timezone, hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(value); return Number(parts.find(part => part.type === "hour")?.value ?? 0) * 60 + Number(parts.find(part => part.type === "minute")?.value ?? 0); }
function dayTitle(value: Date, timezone: string) { return new Intl.DateTimeFormat("ka-GE", { timeZone: timezone, weekday: "short", day: "numeric", month: "short" }).format(dayStart(value, timezone)); }
function dropSlot(event: DragEvent<HTMLDivElement>, day: Date, timezone: string) { const rect = event.currentTarget.getBoundingClientRect(); const rawMinutes = FIRST_HOUR * 60 + Math.round((event.clientY - rect.top) / (15 * PIXELS_PER_MINUTE)) * 15; const minutes = Math.max(FIRST_HOUR * 60, Math.min((LAST_HOUR - 1) * 60 + 45, rawMinutes)); return zonedDateTimeToUtc({ year: day.getUTCFullYear(), month: day.getUTCMonth() + 1, day: day.getUTCDate(), hour: Math.floor(minutes / 60), minute: minutes % 60, second: 0 }, timezone); }

export default function Calendar() {
  const organizations = trpc.organizations.listMine.useQuery();
  const organizationEntry = organizations.data?.[0];
  const organization = organizationEntry?.organization;
  const isStaff = organizationEntry?.membership.role === "STAFF";
  const canManageCalendar = ["OWNER", "MANAGER"].includes(organizationEntry?.membership.role ?? "");
  const utils = trpc.useUtils();
  const locations = trpc.organizations.listLocations.useQuery({ organizationId: organization?.id ?? "" }, { enabled: Boolean(organization?.id) });
  const [activeLocationId, setActiveLocationId] = useState("");
  const selectedLocation = locations.data?.find(location => location.id === activeLocationId) ?? locations.data?.[0];
  const timezone = selectedLocation?.timezone ?? organization?.defaultTimezone ?? "Asia/Tbilisi";
  const [view, setView] = useState<"day" | "week">("day");
  const [cursor, setCursor] = useState(() => startOfWeek(new Date()));
  const [staffFilter, setStaffFilter] = useState("ALL");

  useEffect(() => { if (!activeLocationId && locations.data?.[0]) setActiveLocationId(locations.data[0].id); }, [activeLocationId, locations.data]);

  const days = useMemo(() => view === "week" ? Array.from({ length: 7 }, (_, index) => addDays(startOfWeek(cursor), index)) : [cursor], [cursor, view]);
  const range = useMemo(() => ({ startsAt: dayStart(days[0], timezone), endsAt: dayStart(addDays(days[days.length - 1], 1), timezone) }), [days, timezone]);
  const calendarInput = useMemo(() => ({ organizationId: organization?.id ?? "", locationId: selectedLocation?.id, ...range, staffProfileId: staffFilter === "ALL" ? undefined : staffFilter }), [organization?.id, range, selectedLocation?.id, staffFilter]);
  const appointments = trpc.appointments.listRange.useQuery(calendarInput, { enabled: Boolean(organization?.id && selectedLocation?.id) });
  const staff = trpc.staff.list.useQuery({ organizationId: organization?.id ?? "", locationId: selectedLocation?.id }, { enabled: Boolean(organization?.id && selectedLocation?.id) });
  const updateStatus = trpc.appointments.updateStatus.useMutation({ onSuccess: async () => { await Promise.all([utils.appointments.listRange.invalidate(), utils.appointments.dashboard.invalidate()]); toast.success("ჯავშნის სტატუსი განახლდა."); }, onError: () => toast.error("სტატუსის განახლება ვერ მოხერხდა.") });
  const reschedule = trpc.appointments.reschedule.useMutation({ onSuccess: async () => { await Promise.all([utils.appointments.listRange.invalidate(), utils.appointments.dashboard.invalidate()]); toast.success("ჯავშანი კალენდარში განახლდა."); }, onError: error => toast.error(error.message || "ჯავშნის გადატანა ვერ მოხერხდა.") });
  const visibleStaff = useMemo(() => {
    const all = staff.data ?? [];
    if (isStaff) return all.filter(item => item.membership.id === organizationEntry?.membership.id);
    if (staffFilter !== "ALL") return all.filter(item => item.profile.id === staffFilter);
    return all;
  }, [isStaff, organizationEntry?.membership.id, staff.data, staffFilter]);
  const periodLabel = view === "week" ? `${dayTitle(days[0], timezone)} – ${dayTitle(days[6], timezone)}` : new Intl.DateTimeFormat("ka-GE", { timeZone: timezone, weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(dayStart(days[0], timezone));
  const move = (direction: -1 | 1) => setCursor(current => addDays(current, direction * (view === "week" ? 7 : 1)));
  const switchView = (next: "day" | "week") => { setView(next); setCursor(current => next === "week" ? startOfWeek(current) : current); };
  const calendarAppointments = appointments.data ?? [];

  const advance = (appointment: AppointmentEntry) => { const action = nextAppointmentAction(appointment.status); if (action) updateStatus.mutate({ organizationId: organization!.id, appointmentId: appointment.id, nextStatus: action.status }); };
  const moveAppointment = (appointment: AppointmentEntry, startsAt: Date, staffProfileId?: string) => { if (!organization || !canManageCalendar) return; reschedule.mutate({ organizationId: organization.id, appointmentId: appointment.id, startsAt, staffProfileId, reason: "CALENDAR_DRAG_DROP" }); };
  return <DashboardLayout><div className="sf-workspace-page mx-auto w-full max-w-7xl space-y-5"><WorkspacePageHeader eyebrow="გუნდის ოპერაციები" title="კალენდარი" description={`${periodLabel} · ფილიალისა და სპეციალისტის მიხედვით დალაგებული დროითი ჯავშნები.`} actions={<>{locations.data?.length ? <Select value={activeLocationId || locations.data[0]?.id} onValueChange={setActiveLocationId}><SelectTrigger className="min-w-48 bg-card"><MapPin className="mr-2 h-4 w-4 text-primary" /><SelectValue placeholder="ფილიალი" /></SelectTrigger><SelectContent>{locations.data.map(location => <SelectItem key={location.id} value={location.id}>{location.name}</SelectItem>)}</SelectContent></Select> : null}<div className="flex rounded-xl border border-border bg-card p-1"><Button variant={view === "day" ? "default" : "ghost"} size="sm" onClick={() => switchView("day")}>დღე</Button><Button variant={view === "week" ? "default" : "ghost"} size="sm" onClick={() => switchView("week")}>კვირა</Button></div></>} />
    {organizations.isLoading ? <WorkspaceState kind="loading" title="სამუშაო სივრცე იტვირთება…" /> : null}{organizations.isError ? <WorkspaceState kind="error" title="სამუშაო სივრცის მონაცემები მიუწვდომელია" /> : null}{!organizations.isLoading && !organizations.isError && !organization ? <WorkspaceState kind="empty" title="ჯერ შექმენით სამუშაო სივრცე" description="კალენდარი ხელმისაწვდომი გახდება პირველი ფილიალის შექმნის შემდეგ." /> : null}
    {organization ? <><WorkspaceFilterBar><div className="flex items-center gap-2"><Button variant="outline" size="icon" onClick={() => move(-1)} aria-label="წინა პერიოდი"><ChevronLeft className="h-4 w-4" /></Button><p className="min-w-48 text-center text-sm font-semibold">{periodLabel}</p><Button variant="outline" size="icon" onClick={() => move(1)} aria-label="შემდეგი პერიოდი"><ChevronRight className="h-4 w-4" /></Button></div>{!isStaff ? <Select value={staffFilter} onValueChange={setStaffFilter}><SelectTrigger className="w-full bg-card sm:w-64"><SelectValue placeholder="ყველა სპეციალისტი" /></SelectTrigger><SelectContent><SelectItem value="ALL">ყველა სპეციალისტი</SelectItem>{staff.data?.map(item => <SelectItem key={item.profile.id} value={item.profile.id}>{item.profile.publicDisplayName}</SelectItem>)}</SelectContent></Select> : <p className="text-sm text-muted-foreground">ნაჩვენებია მხოლოდ თქვენი განრიგი.</p>}<WorkspaceStatusPill tone="info">{appointments.isLoading ? "…" : `${calendarAppointments.length} ჯავშანი`}</WorkspaceStatusPill></WorkspaceFilterBar><WorkspaceSection title={view === "day" ? "დღის განრიგი" : "კვირის განრიგი"} description={`${canManageCalendar ? "გადათრიეთ pending/confirmed ბლოკი სხვა დროზე ან სპეციალისტზე · " : ""}აქტიური ფილიალი · ${timezone}`} action={<WorkspaceStatusPill tone="neutral">{visibleStaff.length} სპეციალისტი</WorkspaceStatusPill>}>{locations.isLoading || appointments.isLoading || staff.isLoading ? <WorkspaceState kind="loading" title="კალენდარი იტვირთება…" /> : null}{locations.isError || appointments.isError || staff.isError ? <WorkspaceState kind="error" title="კალენდრის მონაცემები ვერ ჩაიტვირთა" /> : null}{!locations.isLoading && !locations.data?.length ? <WorkspaceState kind="empty" title="ჯერ არ არის აქტიური ფილიალი" /> : null}{!appointments.isLoading && !staff.isLoading && selectedLocation && !visibleStaff.length ? <WorkspaceState kind="empty" title="ამ ფილიალზე სპეციალისტი არ არის მიბმული" description="დაამატეთ სპეციალისტი გუნდის გვერდიდან." /> : null}{!appointments.isLoading && !staff.isLoading && visibleStaff.length ? <><div className="lg:hidden"><AgendaList appointments={calendarAppointments} timezone={timezone} canManageCalendar={canManageCalendar} onAdvance={advance} isUpdating={updateStatus.isPending || reschedule.isPending} /></div><div className="hidden lg:block">{view === "day" ? <DayResourceGrid day={days[0]} timezone={timezone} staff={visibleStaff.map(item => item.profile)} appointments={calendarAppointments} canManageCalendar={canManageCalendar} onAdvance={advance} onMove={moveAppointment} isUpdating={updateStatus.isPending || reschedule.isPending} /> : <WeekTimeGrid days={days} timezone={timezone} appointments={calendarAppointments} canManageCalendar={canManageCalendar} onAdvance={advance} onMove={moveAppointment} isUpdating={updateStatus.isPending || reschedule.isPending} />}</div></> : null}</WorkspaceSection></> : null}</div></DashboardLayout>;
}

type AppointmentEntry = {
  id: string;
  staffProfileId: string;
  startsAt: Date;
  endsAt: Date;
  status: string;
  client: { firstName: string; lastName: string | null } | null;
  staff: { id: string; publicDisplayName: string; color: string };
  services: Array<{ id: string; serviceNameSnapshot: string; durationMinutesSnapshot: number; priceTetriSnapshot: number }>;
  payment?: { state: string };
};
type StaffProfile = { id: string; publicDisplayName: string; color: string };

function DayResourceGrid({ day, timezone, staff, appointments, canManageCalendar, onAdvance, onMove, isUpdating }: { day: Date; timezone: string; staff: StaffProfile[]; appointments: AppointmentEntry[]; canManageCalendar: boolean; onAdvance: (appointment: AppointmentEntry) => void; onMove: (appointment: AppointmentEntry, startsAt: Date, staffProfileId?: string) => void; isUpdating: boolean }) {
  const key = dateKeyInTimeZone(dayStart(day, timezone), timezone);
  return <div className="overflow-x-auto rounded-xl border"><div className="grid min-w-[52rem]" style={{ gridTemplateColumns: `4rem repeat(${staff.length}, minmax(13rem, 1fr))` }}><div className="border-b bg-muted/30" />{staff.map(member => <div key={member.id} className="border-b border-l bg-muted/30 px-3 py-3"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: member.color }} /><p className="truncate text-sm font-semibold">{member.publicDisplayName}</p></div><p className="mt-1 text-xs text-muted-foreground">{dayTitle(day, timezone)}</p></div>)}<TimeLabels />{staff.map(member => <TimeColumn key={member.id} day={day} targetStaffProfileId={member.id} timezone={timezone} appointments={appointments.filter(appointment => appointment.staffProfileId === member.id && dateKeyInTimeZone(new Date(appointment.startsAt), timezone) === key)} canManageCalendar={canManageCalendar} onAdvance={onAdvance} onMove={onMove} isUpdating={isUpdating} />)}</div></div>;
}

function WeekTimeGrid({ days, timezone, appointments, canManageCalendar, onAdvance, onMove, isUpdating }: { days: Date[]; timezone: string; appointments: AppointmentEntry[]; canManageCalendar: boolean; onAdvance: (appointment: AppointmentEntry) => void; onMove: (appointment: AppointmentEntry, startsAt: Date, staffProfileId?: string) => void; isUpdating: boolean }) {
  return <div className="overflow-x-auto rounded-xl border"><div className="grid min-w-[74rem]" style={{ gridTemplateColumns: "4rem repeat(7, minmax(10rem, 1fr))" }}><div className="border-b bg-muted/30" />{days.map(day => <div key={day.toISOString()} className="border-b border-l bg-muted/30 px-3 py-3"><p className="text-sm font-semibold">{dayTitle(day, timezone)}</p><p className="mt-1 text-xs text-muted-foreground">{appointments.filter(appointment => dateKeyInTimeZone(new Date(appointment.startsAt), timezone) === dateKeyInTimeZone(dayStart(day, timezone), timezone)).length} ჯავშანი</p></div>)}<TimeLabels />{days.map(day => <TimeColumn key={day.toISOString()} day={day} timezone={timezone} compact appointments={appointments.filter(appointment => dateKeyInTimeZone(new Date(appointment.startsAt), timezone) === dateKeyInTimeZone(dayStart(day, timezone), timezone))} canManageCalendar={canManageCalendar} onAdvance={onAdvance} onMove={onMove} isUpdating={isUpdating} />)}</div></div>;
}

function TimeLabels() { return <div className="relative h-[780px] bg-muted/20">{hours.map(hour => <p key={hour} className="absolute right-2 -translate-y-2 text-[11px] text-muted-foreground" style={{ top: `${(hour - FIRST_HOUR) * 60}px` }}>{String(hour).padStart(2, "0")}:00</p>)}</div>; }

function TimeColumn({ day, targetStaffProfileId, timezone, appointments, compact = false, canManageCalendar, onAdvance, onMove, isUpdating }: { day: Date; targetStaffProfileId?: string; timezone: string; appointments: AppointmentEntry[]; compact?: boolean; canManageCalendar: boolean; onAdvance: (appointment: AppointmentEntry) => void; onMove: (appointment: AppointmentEntry, startsAt: Date, staffProfileId?: string) => void; isUpdating: boolean }) { const drop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); if (!canManageCalendar || isUpdating) return; const encoded = event.dataTransfer.getData("application/x-salonflow-appointment"); if (!encoded) return; try { const appointment = JSON.parse(encoded) as AppointmentEntry; onMove(appointment, dropSlot(event, day, timezone), targetStaffProfileId); } catch { /* malformed drag payload is ignored */ } }; return <div onDragOver={event => { if (canManageCalendar) event.preventDefault(); }} onDrop={drop} className={`relative h-[780px] border-l bg-[repeating-linear-gradient(to_bottom,transparent,transparent_59px,hsl(var(--border)/0.7)_60px)] ${canManageCalendar ? "transition-colors hover:bg-primary/5" : ""}`}>{appointments.map(appointment => <AppointmentCard key={appointment.id} appointment={appointment} timezone={timezone} compact={compact} canManageCalendar={canManageCalendar} onAdvance={onAdvance} isUpdating={isUpdating} />)}</div>; }

function AgendaList({ appointments, timezone, canManageCalendar, onAdvance, isUpdating }: { appointments: AppointmentEntry[]; timezone: string; canManageCalendar: boolean; onAdvance: (appointment: AppointmentEntry) => void; isUpdating: boolean }) { const ordered = [...appointments].sort((a, b) => new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime()); if (!ordered.length) return <WorkspaceState kind="empty" title="არჩეულ პერიოდში ჯავშანი არ არის" description="შეცვალეთ თარიღი, ფილიალი ან სპეციალისტის ფილტრი." />; return <div className="divide-y divide-border/70">{ordered.map(appointment => { const client = appointment.client ? `${appointment.client.firstName} ${appointment.client.lastName ?? ""}`.trim() : "კლიენტი არ არის მითითებული"; return <article key={appointment.id} className="py-3"><div className="flex gap-3"><div className="w-14 shrink-0 rounded-lg bg-muted px-2 py-1.5 text-center"><p className="font-mono text-sm font-semibold">{formatTimeInTimeZone(new Date(appointment.startsAt), timezone)}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{formatTimeInTimeZone(new Date(appointment.endsAt), timezone)}</p></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><p className="font-semibold">{client}</p><WorkspaceStatusPill tone={appointment.status === "PENDING" ? "warning" : appointment.status === "CANCELLED" || appointment.status === "NO_SHOW" ? "danger" : appointment.status === "IN_SERVICE" ? "violet" : "success"}>{statusLabels[appointment.status] ?? appointment.status}</WorkspaceStatusPill><WorkspaceStatusPill tone={appointment.payment?.state === "PAID" ? "success" : appointment.payment?.state === "PARTIAL" ? "warning" : "neutral"}>{formatPaymentState(appointment.payment?.state)}</WorkspaceStatusPill></div><p className="mt-1 text-sm text-muted-foreground">{appointment.services.map(service => service.serviceNameSnapshot).join(", ") || "სერვისი"}</p><p className="mt-1 text-xs text-muted-foreground">{appointment.staff.publicDisplayName}</p></div>{canManageCalendar ? <AppointmentQuickAction role="RECEPTIONIST" status={appointment.status} cardHeight={70} context="calendar" disabled={isUpdating} onAction={() => onAdvance(appointment)} /> : null}</div></article>; })}</div>; }

function AppointmentCard({ appointment, timezone, compact, canManageCalendar, onAdvance, isUpdating }: { appointment: AppointmentEntry; timezone: string; compact: boolean; canManageCalendar: boolean; onAdvance: (appointment: AppointmentEntry) => void; isUpdating: boolean }) { const startMinute = minuteOfDay(new Date(appointment.startsAt), timezone); const endMinute = minuteOfDay(new Date(appointment.endsAt), timezone); const top = Math.max(0, (startMinute - FIRST_HOUR * 60) * PIXELS_PER_MINUTE + 2); const height = Math.max(42, Math.min((LAST_HOUR - FIRST_HOUR) * 60 - top - 2, (endMinute - startMinute) * PIXELS_PER_MINUTE - 4)); const clientName = appointment.client ? `${appointment.client.firstName} ${appointment.client.lastName ?? ""}`.trim() : "კლიენტი"; const role = canManageCalendar ? "RECEPTIONIST" : "STAFF"; const draggable = canManageCalendar && (appointment.status === "PENDING" || appointment.status === "CONFIRMED"); return <article draggable={draggable} onDragStart={event => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("application/x-salonflow-appointment", JSON.stringify(appointment)); }} title={draggable ? "გადათრიეთ სხვა დროზე ან სპეციალისტზე" : undefined} className={`absolute inset-x-1 overflow-hidden rounded-lg border px-2 py-1.5 shadow-sm ${draggable ? "cursor-grab active:cursor-grabbing" : ""} ${statusTone[appointment.status] ?? "border-primary/30 bg-primary/10 text-primary"}`} style={{ top: `${top}px`, height: `${height}px`, borderLeftWidth: "3px", borderLeftColor: appointment.staff.color }} aria-label={`${formatTimeInTimeZone(new Date(appointment.startsAt), timezone)} ${clientName}`}><p className="truncate text-xs font-semibold">{formatTimeInTimeZone(new Date(appointment.startsAt), timezone)} · {clientName}</p><p className="mt-0.5 truncate text-[11px] leading-4 opacity-85">{appointment.services.map(service => service.serviceNameSnapshot).join(", ") || "სერვისი"}</p>{!compact ? <p className="mt-0.5 truncate text-[10px] opacity-75">{statusLabels[appointment.status] ?? appointment.status}</p> : null}<AppointmentQuickAction role={role} status={appointment.status} cardHeight={height} context="calendar" disabled={isUpdating} onAction={() => onAdvance(appointment)} /></article>; }
