import React, { FormEvent, useEffect, useMemo, useState } from "react";
import { Eye, EyeOff, ImagePlus, ShieldCheck, Trash2 } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { fileToImageDataUrl } from "@/lib/imageUpload";
import { WorkspacePageHeader, WorkspaceSection, WorkspaceState, WorkspaceStatusPill } from "@/components/workspace/WorkspacePrimitives";
import { toast } from "sonner";

const formattedVisit = (date: Date) => new Intl.DateTimeFormat("ka-GE", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(date);

export default function ClientGallery() {
  const utils = trpc.useUtils();
  const organizations = trpc.organizations.listMine.useQuery();
  const entry = organizations.data?.[0];
  const organization = entry?.organization;
  const role = entry?.membership.role ?? "";
  const canManageClients = ["OWNER", "MANAGER", "RECEPTIONIST"].includes(role);
  const canPublish = ["OWNER", "MANAGER"].includes(role);
  const clients = trpc.clients.list.useQuery({ organizationId: organization?.id ?? "", limit: 50, offset: 0, status: "ACTIVE" }, { enabled: Boolean(organization?.id && canManageClients) });
  const [clientId, setClientId] = useState("");
  const historyInput = useMemo(() => ({ organizationId: organization?.id ?? "", clientId: clientId || "client_gallery_placeholder", limit: 50 }), [clientId, organization?.id]);
  const history = trpc.clients.bookingHistory.useQuery(historyInput, { enabled: Boolean(organization?.id && clientId) });
  const galleryInput = useMemo(() => ({ organizationId: organization?.id ?? "", clientId: clientId || "client_gallery_placeholder" }), [clientId, organization?.id]);
  const gallery = trpc.media.listClientGallery.useQuery(galleryInput, { enabled: Boolean(organization?.id && clientId && canManageClients) });
  const [appointmentId, setAppointmentId] = useState("");
  const [beforeFile, setBeforeFile] = useState<File | null>(null);
  const [afterFile, setAfterFile] = useState<File | null>(null);
  const [beforeAlt, setBeforeAlt] = useState("");
  const [afterAlt, setAfterAlt] = useState("");
  const [internalNote, setInternalNote] = useState("");
  const [publicationConsent, setPublicationConsent] = useState(false);
  const [requestPublic, setRequestPublic] = useState(false);
  useEffect(() => { if (!clientId && clients.data?.items[0]) setClientId(clients.data.items[0].id); }, [clientId, clients.data]);
  const completedVisits = history.data?.filter(entry => entry.appointment.status === "COMPLETED") ?? [];
  useEffect(() => { if (!appointmentId && completedVisits[0]) setAppointmentId(completedVisits[0].appointment.id); }, [appointmentId, completedVisits]);
  const create = trpc.media.createClientBeforeAfter.useMutation({ onSuccess: async () => { await utils.media.listClientGallery.invalidate(); setBeforeFile(null); setAfterFile(null); setBeforeAlt(""); setAfterAlt(""); setInternalNote(""); setPublicationConsent(false); setRequestPublic(false); toast.success("Before/after ნაკრები დაცულად შეინახა."); }, onError: error => toast.error(error.message || "ფოტოების შენახვა ვერ მოხერხდა.") });
  const setVisibility = trpc.media.setClientGalleryVisibility.useMutation({ onSuccess: () => utils.media.listClientGallery.invalidate(), onError: error => toast.error(error.message || "ხილვადობის შეცვლა ვერ მოხერხდა.") });
  const removeSet = trpc.media.deleteClientGallerySet.useMutation({ onSuccess: () => { utils.media.listClientGallery.invalidate(); toast.success("ფოტოების ნაკრები წაიშალა რეესტრიდან."); }, onError: error => toast.error(error.message || "წაშლა ვერ მოხერხდა.") });
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!organization || !clientId || !appointmentId || !beforeFile || !afterFile) return; try { const [beforeImageDataUrl, afterImageDataUrl] = await Promise.all([fileToImageDataUrl(beforeFile), fileToImageDataUrl(afterFile)]); create.mutate({ organizationId: organization.id, clientId, appointmentId, beforeImageDataUrl, afterImageDataUrl, beforeAltTextKa: beforeAlt, afterAltTextKa: afterAlt, internalNote: internalNote || undefined, clientPublicationConsent: publicationConsent, requestPublicVisibility: canPublish && requestPublic }); } catch (error) { toast.error(error instanceof Error ? error.message : "ფოტოების წაკითხვა ვერ მოხერხდა."); } };
  return <DashboardLayout><main className="sf-workspace-page mx-auto w-full max-w-7xl space-y-5"><WorkspacePageHeader eyebrow="კლიენტის კარტოთეკა" title="Before / after გალერეა" description="ვიზიტთან მიბმული შედეგები private-ია by default. საჯარო გამოჩენა დასაშვებია მხოლოდ კლიენტის ცალკე თანხმობით და owner/manager approval-ით." />
    {organizations.isLoading ? <WorkspaceState kind="loading" title="გალერეა იტვირთება…" /> : null}{organizations.isError ? <WorkspaceState kind="error" title="გალერეის კონტექსტი მიუწვდომელია" /> : null}{!organizations.isLoading && organization && !canManageClients ? <WorkspaceState kind="empty" title="კლიენტის გალერეის წვდომა არ გაქვთ" description="ეს მასალა დაცულია და ხელმისაწვდომია მხოლოდ უფლებამოსილი სამუშაო გუნდისთვის." /> : null}
    {organization && canManageClients ? <><WorkspaceSection title="კლიენტი და დასრულებული ვიზიტი" description="ფოტოები უკავშირდება მხოლოდ ამ ორგანიზაციის კლიენტსა და დასრულებულ ვიზიტს."><div className="grid gap-3 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="gallery-client">კლიენტი</Label><Select value={clientId} onValueChange={value => { setClientId(value); setAppointmentId(""); }}><SelectTrigger id="gallery-client"><SelectValue placeholder="აირჩიეთ კლიენტი" /></SelectTrigger><SelectContent>{clients.data?.items.map(client => <SelectItem key={client.id} value={client.id}>{client.firstName} {client.lastName ?? ""}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="gallery-visit">დასრულებული ვიზიტი</Label><Select value={appointmentId} onValueChange={setAppointmentId} disabled={!clientId || history.isLoading}><SelectTrigger id="gallery-visit"><SelectValue placeholder={history.isLoading ? "ვიზიტები იტვირთება…" : "აირჩიეთ დასრულებული ვიზიტი"} /></SelectTrigger><SelectContent>{completedVisits.map(entry => <SelectItem key={entry.appointment.id} value={entry.appointment.id}>{formattedVisit(entry.appointment.startsAt)} · {entry.services.map(service => service.serviceNameSnapshot).join(", ") || "მომსახურება"}</SelectItem>)}</SelectContent></Select>{clientId && !history.isLoading && !completedVisits.length ? <p className="text-xs text-muted-foreground">ამ კლიენტს დასრულებული ვიზიტი ჯერ არ აქვს, ამიტომ before/after ვერ დაემატება.</p> : null}</div></div></WorkspaceSection>
      <div className="grid gap-5 xl:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]"><WorkspaceSection title="ახალი შედეგის დამატება" description="გამოიყენეთ რეალური ვიზიტის შედეგები. JPEG, PNG ან WebP; თითო ფოტო მაქსიმუმ 5MB."><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="before-photo">მანამდე</Label><Input id="before-photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={event => setBeforeFile(event.target.files?.[0] ?? null)} required /><Input value={beforeAlt} onChange={event => setBeforeAlt(event.target.value)} placeholder="Alt ტექსტი ქართულად" minLength={3} maxLength={255} required /></div><div className="space-y-2"><Label htmlFor="after-photo">შემდეგ</Label><Input id="after-photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={event => setAfterFile(event.target.files?.[0] ?? null)} required /><Input value={afterAlt} onChange={event => setAfterAlt(event.target.value)} placeholder="Alt ტექსტი ქართულად" minLength={3} maxLength={255} required /></div></div><div className="space-y-2"><Label htmlFor="gallery-note">შიდა შენიშვნა <span className="text-muted-foreground">(არასავალდებულო)</span></Label><Textarea id="gallery-note" value={internalNote} onChange={event => setInternalNote(event.target.value)} maxLength={2000} placeholder="მაგ. გამოყენებული სერვისი ან შემდგომი მოვლის კონტექსტი" /></div><label className="flex items-start gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" checked={publicationConsent} onChange={event => { setPublicationConsent(event.target.checked); if (!event.target.checked) setRequestPublic(false); }} className="mt-0.5 size-4 accent-primary" /><span>კლიენტმა ცალკე დაადასტურა ამ შედეგის საჯარო გამოქვეყნების თანხმობა.</span></label>{canPublish ? <label className="flex items-start gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" checked={requestPublic} disabled={!publicationConsent} onChange={event => setRequestPublic(event.target.checked)} className="mt-0.5 size-4 accent-primary" /><span>ახლავე გამოჩნდეს სალონის საჯარო გვერდზე. ეს შესაძლებელი ხდება მხოლოდ ზემოთ მონიშნული consent-ის შემთხვევაში.</span></label> : null}<Button type="submit" disabled={!clientId || !appointmentId || !beforeFile || !afterFile || create.isPending}><ImagePlus className="mr-2 size-4" />{create.isPending ? "ინახება…" : "Before/after-ის შენახვა"}</Button></form></WorkspaceSection>
        <WorkspaceSection title="კლიენტის დაცული გალერეა" description="აქ ჩანს ამ კლიენტზე მიბმული ყველა შედეგი; public სტატუსი არ ნიშნავს რომ სხვა კლიენტის ინფორმაცია იხსნება.">{gallery.isLoading ? <WorkspaceState kind="loading" title="გალერეა იტვირთება…" /> : null}{gallery.isError ? <WorkspaceState kind="error" title="გალერეის ჩატვირთვა ვერ მოხერხდა" /> : null}{!gallery.isLoading && !gallery.isError && !gallery.data?.length ? <WorkspaceState kind="empty" title="ამ კლიენტისთვის ფოტოები ჯერ არ არის" description="პირველი ნაკრები დასრულებულ ვიზიტს უნდა დაუკავშიროთ." /> : null}<div className="grid gap-4 sm:grid-cols-2">{gallery.data?.map(entry => { const before = entry.items.find(item => item.stage === "BEFORE"); const after = entry.items.find(item => item.stage === "AFTER"); return <article key={entry.set.id} className="overflow-hidden rounded-xl border"><div className="grid grid-cols-2">{before ? <figure><img src={before.url} alt={before.altTextKa || "მომსახურებამდე"} className="aspect-square w-full object-cover" loading="lazy" /><figcaption className="px-3 py-2 text-xs text-muted-foreground">მანამდე</figcaption></figure> : null}{after ? <figure><img src={after.url} alt={after.altTextKa || "მომსახურების შემდეგ"} className="aspect-square w-full object-cover" loading="lazy" /><figcaption className="px-3 py-2 text-xs text-muted-foreground">შემდეგ</figcaption></figure> : null}</div><div className="space-y-3 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><WorkspaceStatusPill tone={entry.set.publicVisible ? "success" : "neutral"}>{entry.set.publicVisible ? "საჯარო" : "private"}</WorkspaceStatusPill>{entry.set.clientPublicationConsent ? <span className="inline-flex items-center gap-1 text-xs text-muted-foreground"><ShieldCheck className="size-3.5 text-primary" />consent დაფიქსირებულია</span> : null}</div>{entry.set.internalNote ? <p className="text-sm text-muted-foreground">{entry.set.internalNote}</p> : null}<div className="flex gap-2">{canPublish ? <Button size="sm" variant="outline" disabled={setVisibility.isPending || (entry.set.publicVisible ? false : !entry.set.clientPublicationConsent)} onClick={() => setVisibility.mutate({ organizationId: organization.id, setId: entry.set.id, publicVisible: !entry.set.publicVisible })}>{entry.set.publicVisible ? <><EyeOff className="mr-1.5 size-3.5" />დამალვა</> : <><Eye className="mr-1.5 size-3.5" />საჯაროდ გამოჩენა</>}</Button> : null}<Button size="sm" variant="ghost" disabled={removeSet.isPending} onClick={() => removeSet.mutate({ organizationId: organization.id, setId: entry.set.id })}><Trash2 className="mr-1.5 size-3.5" />წაშლა</Button></div></div></article>; })}</div></WorkspaceSection>
      </div></> : null}
  </main></DashboardLayout>;
}
