import { Button } from "@/components/ui/button";
import { PublicEyebrow, PublicFooter, PublicHeader } from "@/components/public/PublicPrimitives";
import { usePublicMeta } from "@/components/public/PublicMeta";
import { ArrowRight, CalendarDays, CheckCircle2, CreditCard, KeyRound, LayoutDashboard, ShieldCheck, UsersRound } from "lucide-react";
import React from "react";
import { Link } from "wouter";

const groups = [
  { icon: CalendarDays, title: "ჩაწერები და კალენდარი", text: "დღის queue, day/week კალენდარი, სწრაფი ჩაწერა და conflict-safe დროის გადამოწმება ერთ ოპერაციულ ხედში.", items: ["ფილიალის timezone კონტექსტი", "სპეციალისტების სვეტები", "უსაფრთხო გადატანა და სტატუსები"] },
  { icon: UsersRound, title: "კლიენტები და გუნდი", text: "კლიენტის ისტორია, თანხმობები, თანამშრომლების ხელმისაწვდომობა და სამუშაო საათები რეალური role scope-ით.", items: ["ძიებადი კლიენტების რეესტრი", "ფილიალზე მიბმული სპეციალისტები", "განრიგის წესები და გამონაკლისები"] },
  { icon: CreditCard, title: "ფინანსები და ანგარიშები", text: "GEL/tetri სიზუსტით შემოსავალი, ხარჯები, საკომისიო და გადახდის სტატუსები, არსებული ანგარიშების მონაცემებზე დაფუძნებით.", items: ["დაცული CSV export", "პერიოდის მიხედვით ანალიტიკა", "გადახდის მეთოდების ქართული label-ები"] },
  { icon: ShieldCheck, title: "ონლაინ ჩაწერა", text: "სერვისი, სპეციალისტი ან თავისუფალი არჩევანი, ხელმისაწვდომობის server-side check და საბოლოო დადასტურება.", items: ["მობილურ-first booking flow", "იდემპოტენტური დადასტურება", "როლებისა და scope-ის დაცვა"] },
];

const faq = [
  ["ვისთვის არის SalonFlow?", "SalonFlow შექმნილია სალონების, სპა სივრცეების და მომსახურებაზე დაფუძნებული გუნდების ყოველდღიური ოპერაციების სამართავად."],
  ["არის თუ არა მრავალფილიალიანი მხარდაჭერა?", "დიახ. სამუშაო სივრცე ორგანიზაციასა და აქტიურ ფილიალებს აერთიანებს IANA timezone და public booking slug კონტექსტით."],
  ["როგორ მუშაობს ონლაინ ჩაწერა?", "სტუმარი ირჩევს აქტიურ მომსახურებას, სპეციალისტს ან თავისუფალ არჩევანს, დროსა და საჭირო კონტაქტს. საბოლოო ჩაწერამდე სისტემა ხელმისაწვდომობას ხელახლა ამოწმებს."],
  ["იგზავნება თუ არა შეტყობინებები?", "ავტომატური email/SMS მიწოდება ჯერ არ არის ჩართული, რადგან verified sender domain და provider configuration ჯერ არ არის დამატებული."],
];

function MarketingLayout({ eyebrow, title, description, canonicalPath, children }: { eyebrow: string; title: string; description: string; canonicalPath: string; children: React.ReactNode }) {
  usePublicMeta({ title: `${eyebrow} | SalonFlow`, description, canonicalPath });
  return <div className="sf-public-page"><PublicHeader /><main id="main-content" tabIndex={-1}><section className="sf-salon-section"><div className="sf-public-container pb-12 pt-14 sm:pb-16 sm:pt-20"><p className="sf-salon-eyebrow">{eyebrow}</p><div className="sf-editorial-rule mt-5" /><h1 className="sf-display mt-5 max-w-4xl text-[2.4rem] leading-[1.02] sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--sf-muted)]">{description}</p></div></section>{children}</main><PublicFooter /></div>;
}

function PageCTA({ title, description, secondary = true }: { title: string; description: string; secondary?: boolean }) { return <section className="sf-public-container pb-20 pt-10 sm:pb-28"><div className="sf-salon-media-frame sf-grain relative px-6 py-12 text-white shadow-[var(--sf-glow-brand)] sm:px-10 sm:py-16" style={{ background: "var(--sf-gradient-brand)" }}><span className="sf-blob" style={{ width: "22rem", height: "22rem", top: "-7rem", right: "-4rem", background: "rgba(255,255,255,0.32)", opacity: 0.5, animation: "sf-blob-morph 16s ease-in-out infinite" }} aria-hidden="true" /><div className="relative max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.13em] text-white/75">SalonFlow</p><h2 className="sf-display mt-3 text-3xl leading-tight sm:text-5xl">{title}</h2><p className="mt-4 leading-7 text-white/85">{description}</p><div className="sf-salon-cta-row mt-7"><Button asChild size="lg" className="bg-white text-[var(--sf-accent-strong)] hover:bg-white/90 hover:-translate-y-0.5"><Link href="/register">სამუშაო სივრცის გახსნა <ArrowRight className="size-4" /></Link></Button>{secondary ? <Button asChild variant="outline" size="lg" className="border-white/40 bg-white/10 text-white hover:bg-white/20 hover:text-white"><Link href="/book">ონლაინ ჩაწერის ნახვა</Link></Button> : null}</div></div></div></section>; }

export function FeaturesPage() { return <MarketingLayout eyebrow="შესაძლებლობები" title="ერთი workflow — ჩაწერებიდან ანგარიშებამდე." description="SalonFlow აერთიანებს მხოლოდ იმ ოპერაციულ მოდულებს, რომლებიც უკვე მხარდაჭერილია პროდუქტში და რეალურ role/organization საზღვრებს იცავს." canonicalPath="/features"><section className="sf-salon-section"><div className="sf-public-container grid gap-4 py-14 md:grid-cols-2 lg:py-20">{groups.map(({ icon: Icon, title, text, items }) => <article key={title} className="sf-salon-panel p-6 sm:p-7"><span className="grid size-11 place-items-center rounded-xl bg-[color-mix(in_srgb,var(--sf-salon-warm)_13%,transparent)] text-[var(--sf-salon-warm)]"><Icon className="size-5" /></span><h2 className="mt-5 text-2xl font-semibold tracking-tight">{title}</h2><p className="mt-3 leading-7 text-[var(--sf-muted)]">{text}</p><ul className="sf-salon-ready-list mt-6 text-sm">{items.map(item => <li key={item}><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[var(--sf-jade)]" />{item}</li>)}</ul></article>)}</div></section><PageCTA title="თქვენი ყოველდღიური პროცესები უფრო მშვიდ workflow-ში." description="შექმენით სამუშაო სივრცე, დაამატეთ პირველი ფილიალი და დაიწყეთ არსებული, დაცული ფუნქციებით." /></MarketingLayout>; }

export function PricingPage() { return <MarketingLayout eyebrow="ტარიფები" title="ფასები უნდა იყოს ისეთივე მკაფიო, როგორც თქვენი ოპერაციები." description="SalonFlow-ის ამ deployment-ში subscription გეგმები, billing rules და გამოქვეყნებული ფასები ჯერ არ არის კონფიგურირებული. ამიტომ არ ვაჩვენებთ გამოგონილ ტარიფებს ან პირობებს." canonicalPath="/pricing"><section className="sf-public-container pb-14"><div className="sf-salon-panel max-w-3xl p-7 sm:p-10"><span className="grid size-11 place-items-center rounded-xl bg-[color-mix(in_srgb,var(--sf-amber)_16%,transparent)] text-[var(--sf-amber)]"><CreditCard className="size-5" /></span><h2 className="mt-5 text-2xl font-semibold">გამჭვირვალე ინფორმაცია გამოქვეყნდება მხოლოდ რეალური billing configuration-ის შემდეგ.</h2><p className="mt-4 max-w-2xl leading-7 text-[var(--sf-muted)]">მანამდე შეგიძლიათ შექმნათ local ანგარიში და გაეცნოთ არსებულ სამუშაო/booking გამოცდილებას. ეს გვერდი შეგნებულად არ ასახელებს გეგმებს, რეკომენდაციებს, ფასებს ან ვალდებულებებს, რომლებიც სისტემაში ჯერ არ არსებობს.</p><div className="sf-salon-note mt-6"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-[var(--sf-salon-leaf)]" aria-hidden="true" /><p>ამ გვერდზე არ ჩნდება subscription ან გადახდის ვალდებულება, სანამ billing წესები რეალურად არ კონფიგურდება.</p></div><Button asChild variant="public" size="lg" className="mt-7"><Link href="/register">ანგარიშის შექმნა <ArrowRight className="size-4" /></Link></Button></div></section><PageCTA title="პროდუქტის შემოწმება რეალური workflow-ით დაიწყეთ." description="შექმენით საკუთარი დაცული სამუშაო სივრცე და ნახეთ არსებული ოპერაციული გამოცდილება." secondary={false} /></MarketingLayout>; }

export function DemoPage() { return <MarketingLayout eyebrow="პროდუქტის დათვალიერება" title="იხილეთ workflow, არა გამოგონილი dashboard." description="საჯარო ვიზუალები ასახავს SalonFlow-ის მხარდაჭერილ კალენდრის, კლიენტის, გუნდის, ანგარიშების და ონლაინ ჩაწერის კონცეფტებს; საჯარო shared demo workspace არ არის ჩართული, რათა რეალური მონაცემის კონფიდენციალურობა შენარჩუნდეს." canonicalPath="/demo"><section className="sf-public-container grid gap-4 pb-14 md:grid-cols-3"><DemoTile icon={LayoutDashboard} title="ოპერაციები" text="Today queue, სტატუსები და სწრაფი მოქმედებები." /><DemoTile icon={CalendarDays} title="კალენდარი" text="სპეციალისტების დრო, ხელმისაწვდომობა და უსაფრთხო გადატანა." /><DemoTile icon={KeyRound} title="ონლაინ ჩაწერა" text="მომსახურება, სპეციალისტი, დრო და დადასტურება." /></section><PageCTA title="თქვენი რეალური მონაცემი თქვენს სივრცეში." description="რეგისტრაციისა და onboarding-ის შემდეგ SalonFlow ქმნის ორგანიზაციას, პირველ ფილიალსა და დაცულ სამუშაო კონტექსტს." /></MarketingLayout>; }
function DemoTile({ icon: Icon, title, text }: { icon: typeof LayoutDashboard; title: string; text: string }) { return <article className="sf-salon-panel p-6"><Icon className="size-5 text-[var(--sf-salon-warm)]" /><h2 className="mt-5 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-[var(--sf-muted)]">{text}</p></article>; }

export function FaqPage() { return <MarketingLayout eyebrow="ხშირი კითხვები" title="სანამ დაიწყებთ, პასუხები ხელთ გქონდეთ." description="SalonFlow-ის მიმდინარე ხელმისაწვდომი ფუნქციები, უსაფრთხოება და შეგნებულად გადადებული ინტეგრაციები აღწერილია პირდაპირ — ზედმეტი დაპირებების გარეშე." canonicalPath="/faq"><section className="sf-public-container pb-16"><div className="sf-salon-panel divide-y divide-[var(--sf-line)] overflow-hidden">{faq.map(([question, answer]) => <details key={question} className="group px-6 py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-semibold"><span>{question}</span><ArrowRight className="size-4 shrink-0 text-[var(--sf-salon-warm)] transition-transform group-open:rotate-90" /></summary><p className="mt-3 max-w-3xl text-sm leading-7 text-[var(--sf-muted)]">{answer}</p></details>)}</div></section><PageCTA title="თუ მზად ხართ, დაიწყეთ პირველი ფილიალით." description="SalonFlow-ის setup flow ნაბიჯ-ნაბიჯ აგროვებს მხოლოდ იმ მონაცემს, რომელიც თქვენს პირველ ოპერაციულ დღეს სჭირდება." /></MarketingLayout>; }

export function ContactPage() { return <MarketingLayout eyebrow="კონტაქტი" title="კონტაქტის არხი უნდა იყოს რეალური, არა დეკორაცია." description="ამ ეტაპზე SalonFlow-ში არ არის კონფიგურირებული საჯარო მხარდაჭერის ფორმა, email მისამართი ან ticketing integration. ამიტომ ეს გვერდი არ გვაჩვენებს გამოგონილ საკონტაქტო არხს." canonicalPath="/contact"><section className="sf-public-container pb-16"><div className="sf-salon-panel max-w-3xl p-7 sm:p-10"><span className="grid size-11 place-items-center rounded-xl bg-[color-mix(in_srgb,var(--sf-salon-leaf)_14%,transparent)] text-[var(--sf-salon-leaf)]"><ShieldCheck className="size-5" /></span><h2 className="mt-5 text-2xl font-semibold">უსაფრთხო ანგარიშის გამოცდილება უკვე ხელმისაწვდომია.</h2><p className="mt-4 leading-7 text-[var(--sf-muted)]">შექმენით ან შედით თქვენს ადგილობრივ ანგარიშში, რათა გახსნათ საკუთარი სამუშაო სივრცე. საჯარო საკონტაქტო არხები დაემატება მხოლოდ მაშინ, როდესაც მათი რეალური მომსახურების პროცესი და პასუხის პასუხისმგებელი მხარე განსაზღვრული იქნება.</p><div className="sf-salon-note mt-6"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-[var(--sf-salon-leaf)]" aria-hidden="true" /><p>არასოდეს ვაჩვენებთ email-ს ან ფორმას, რომელსაც რეალური პასუხის პროცესი არ აქვს.</p></div><div className="sf-salon-cta-row mt-7"><Button asChild variant="public" size="lg"><Link href="/register">რეგისტრაცია <ArrowRight className="size-4" /></Link></Button><Button asChild variant="publicSecondary" size="lg"><Link href="/login">არსებულ ანგარიშში შესვლა</Link></Button></div></div></section></MarketingLayout>; }
