import { marketplaceDiscoveryFilters, marketplaceDiscoveryHref, MarketplaceCategoryRail, MarketplaceListingCard } from "@/components/public/MarketplaceDiscovery";
import { PublicFooter, PublicHeader } from "@/components/public/PublicPrimitives";
import { usePublicMeta } from "@/components/public/PublicMeta";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Crown, Map, Search, ShieldCheck, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";

function PromotionSection({ title, description, icon, items, tone }: { title: string; description: string; icon: React.ReactNode; items: any[]; tone: "vip" | "recommended" }) {
  if (!items.length) return null;
  return <section className={`mt-10 rounded-[var(--sf-radius-surface)] border p-5 sm:p-6 ${tone === "vip" ? "border-[color-mix(in_srgb,var(--sf-fuchsia)_34%,var(--sf-line))] bg-[radial-gradient(circle_at_88%_0%,color-mix(in_srgb,var(--sf-fuchsia)_16%,transparent),transparent_30%),var(--sf-surface-raised)]" : "border-[color-mix(in_srgb,var(--sf-amber)_42%,var(--sf-line))] bg-[radial-gradient(circle_at_88%_0%,color-mix(in_srgb,var(--sf-amber)_17%,transparent),transparent_30%),var(--sf-surface-raised)]"}`} aria-labelledby={`${tone}-salons-title`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="sf-salon-eyebrow">PAID PLACEMENT · NOT A RATING</p><h2 id={`${tone}-salons-title`} className="mt-2 flex items-center gap-2 text-2xl font-bold">{icon}{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--sf-muted)]">{description}</p></div><span className="rounded-full border border-[var(--sf-line)] bg-[var(--sf-surface)] px-3 py-1.5 text-xs font-semibold">{items.length} სალონი</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(item => <MarketplaceListingCard key={item.locationId as string} item={item} />)}</div></section>;
}

export default function MarketplaceDirectory() {
  usePublicMeta({ title: "სალონების კატალოგი | SalonFlow", description: "იპოვეთ მხოლოდ დამტკიცებული სალონები კატეგორიის, სახელის ან უბნის მიხედვით და გადადით მათ რეალურ public profile-ზე.", canonicalPath: "/salons" });
  const [location, setLocation] = useLocation();
  const initial = () => marketplaceDiscoveryFilters(typeof window === "undefined" ? "" : window.location.search);
  const [categorySlug, setCategorySlug] = useState<string | undefined>(() => initial().categorySlug);
  const [search, setSearch] = useState(() => initial().search);
  const [searchDraft, setSearchDraft] = useState(() => initial().search);
  useEffect(() => { const filters = initial(); setCategorySlug(filters.categorySlug); setSearch(filters.search); setSearchDraft(filters.search); }, [location]);
  useEffect(() => { const timer = window.setTimeout(() => { const nextSearch = searchDraft.trim(); if (nextSearch === search) return; setSearch(nextSearch); setLocation(marketplaceDiscoveryHref("/salons", categorySlug, nextSearch)); }, 250); return () => window.clearTimeout(timer); }, [searchDraft, search, categorySlug, setLocation]);
  const input = useMemo(() => ({ limit: 48, offset: 0, categorySlug, search: search.trim() || undefined }), [categorySlug, search]);
  const directory = trpc.marketplace.directory.useQuery(input);
  const chooseCategory = (nextCategory?: string) => { setCategorySlug(nextCategory); setLocation(marketplaceDiscoveryHref("/salons", nextCategory, searchDraft)); };
  const clearFilters = () => { setSearchDraft(""); setSearch(""); setCategorySlug(undefined); setLocation("/salons"); };
  const items: any[] = directory.data?.items ?? [];
  const vipItems = items.filter(item => item.promotion?.tier === "VIP");
  const recommendedItems = items.filter(item => item.promotion?.tier === "RECOMMENDED");
  const standardItems = items.filter(item => !item.promotion);
  const filterSummary = categorySlug || search.trim();
  const mapHref = marketplaceDiscoveryHref("/salons/map", categorySlug, search);

  return <div className="sf-public-page"><PublicHeader /><main id="main-content" className="sf-salon-section min-h-screen"><div className="sf-public-container py-10 sm:py-14"><div className="max-w-3xl"><p className="sf-salon-eyebrow">SALONFLOW MARKETPLACE</p><h1 className="sf-display mt-4 text-4xl font-semibold leading-tight sm:text-6xl">იპოვეთ სწორი სალონი — სერვისის, სტილისა და ადგილის მიხედვით.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[var(--sf-muted)]">აირჩიეთ კატეგორია ან მოძებნეთ სახელითა და უბნით. „რეკომენდებული“ და „VIP / რეკლამა“ არის ფასიანი გამორჩეული განთავსების მკაფიო ნიშანი — არა მომხმარებლის რეიტინგი.</p></div>
    <div className="mt-8 grid gap-3 lg:grid-cols-[minmax(0,1fr)_auto]"><label className="relative"><span className="sr-only">სალონის ან უბნის ძიება</span><Search className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-[var(--sf-muted)]" aria-hidden="true" /><Input value={searchDraft} onChange={event => setSearchDraft(event.target.value)} placeholder="მოძებნეთ სალონი ან უბანი" className="h-12 rounded-2xl border-[var(--sf-line)] bg-[var(--sf-surface-raised)] pl-11" /></label><Link href={mapHref} data-conversion-event="DIRECTORY_MAP_OPENED" className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl border border-[var(--sf-line)] bg-[var(--sf-surface-raised)] px-5 text-sm font-semibold transition hover:border-[var(--sf-salon-warm)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--sf-accent-strong)]"><Map className="size-4 text-[var(--sf-salon-warm)]" aria-hidden="true" />რუკაზე ნახვა</Link></div>
    <div className="mt-4"><MarketplaceCategoryRail selectedSlug={categorySlug} onSelect={chooseCategory} /></div>
    {filterSummary ? <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--sf-line)] bg-[var(--sf-surface-raised)] px-4 py-3" aria-live="polite"><p className="text-sm font-medium">ფილტრი აქტიურია: {search.trim() ? `„${search.trim()}“` : "არჩეული კატეგორია"}</p><button type="button" onClick={clearFilters} className="inline-flex min-h-10 items-center gap-1.5 text-sm font-semibold text-[var(--sf-salon-warm)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--sf-accent-strong)]"><X className="size-4" aria-hidden="true" />ფილტრის გასუფთავება</button></div> : null}
    <div className="mt-8 flex items-center gap-2 text-xs text-[var(--sf-muted)]"><ShieldCheck className="size-4 text-[var(--sf-jade)]" aria-hidden="true" />კატალოგში ჩანს მხოლოდ დამტკიცებული listing; availability საბოლოოდ booking flow-ში მოწმდება.</div>
    {directory.isLoading ? <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="sf-skeleton h-80 rounded-[var(--sf-radius-surface)]" />)}</div> : null}{directory.isError ? <div className="mt-8 rounded-[var(--sf-radius-surface)] border border-dashed p-8" role="alert"><h2 className="font-semibold">კატალოგი ახლა მიუწვდომელია</h2><p className="mt-2 text-sm text-[var(--sf-muted)]">სცადეთ რამდენიმე წუთში ხელახლა.</p></div> : null}{!directory.isLoading && !directory.isError && !items.length ? <div className="mt-8 rounded-[var(--sf-radius-surface)] border border-dashed bg-[var(--sf-surface-raised)] p-8"><h2 className="text-xl font-semibold">ამ ფილტრში სალონი ჯერ არ არის.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[var(--sf-muted)]">სცადეთ სხვა კატეგორია ან ძიების სიტყვა. VIP და რეკომენდებული სექციები სწორედ აქ გამოჩნდება მხოლოდ მას შემდეგ, რაც platform admin რეალურ, დამტკიცებულ სალონს აქტიურ პერიოდს დაუნიშნავს. არ ვაჩვენებთ დემო ან გამოგონილ სალონებს.</p></div> : null}
    {!directory.isLoading && !directory.isError ? <><PromotionSection title="VIP / რეკლამა" description="ეს არის platform-admin-ის მიერ აქტიური პერიოდით მინიჭებული სარეკლამო განთავსება; არ წარმოადგენს მომხმარებლის შეფასებას ან ხარისხის რეიტინგს." icon={<Crown className="size-5 text-[var(--sf-fuchsia)]" aria-hidden="true" />} items={vipItems} tone="vip" /><PromotionSection title="რეკომენდებული" description="ეს არის მკაფიოდ მონიშნული ფასიანი განთავსება. სალონის პოზიცია არ ეფუძნება შეფასებებს ან გამოგონილ პოპულარობას." icon={<Sparkles className="size-5 text-[var(--sf-amber)]" aria-hidden="true" />} items={recommendedItems} tone="recommended" />{standardItems.length ? <section className="mt-10" aria-labelledby="all-salons-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="sf-salon-eyebrow">APPROVED SALONS</p><h2 id="all-salons-title" className="mt-2 text-2xl font-bold">სხვა დამტკიცებული სალონები</h2></div><span className="text-sm text-[var(--sf-muted)]">{standardItems.length} სალონი</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{standardItems.map(item => <MarketplaceListingCard key={item.locationId as string} item={item} />)}</div></section> : null}</> : null}
  </div></main><PublicFooter /></div>;
}
