import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicPrimitives";
import { ArrowLeft, Compass, Home, Map } from "lucide-react";
import { useLocation } from "wouter";

export default function NotFound() {
  const [, setLocation] = useLocation();
  return <div className="sf-public-page flex min-h-screen flex-col"><PublicHeader /><main className="sf-public-container flex flex-1 items-center py-14 sm:py-20"><section className="mx-auto w-full max-w-2xl text-center"><div className="sf-surface overflow-hidden"><div className="border-b border-[var(--sf-line)] bg-[color-mix(in_srgb,var(--sf-terracotta)_6%,transparent)] px-6 py-7 sm:px-10 sm:py-9"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[color-mix(in_srgb,var(--sf-terracotta)_12%,transparent)] text-[var(--sf-terracotta)]"><Compass className="size-7" aria-hidden="true" /></span><p className="sf-kicker mt-5">404 · გზა ვერ მოიძებნა</p><h1 className="sf-display mt-3 text-4xl font-semibold leading-tight sm:text-5xl">ეს გვერდი ვერ ვიპოვეთ.</h1></div><div className="px-6 py-7 sm:px-10 sm:py-9"><p className="mx-auto max-w-lg text-sm leading-7 text-[var(--sf-muted)]">მისამართი შეიძლება არასწორია, შეიცვალა ან აღარ არსებობს. დაბრუნდით მთავარ გვერდზე ან გამოიყენეთ წინა გვერდი, რათა უსაფრთხოდ გააგრძელოთ.</p><div id="not-found-button-group" className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button variant="public" onClick={() => setLocation("/")}><Home className="size-4" aria-hidden="true" />მთავარ გვერდზე დაბრუნება</Button><Button variant="publicSecondary" onClick={() => window.history.back()}><ArrowLeft className="size-4" aria-hidden="true" />წინა გვერდი</Button></div><p className="mt-7 inline-flex items-center gap-2 text-xs text-[var(--sf-muted)]"><Map className="size-3.5" aria-hidden="true" />თუ ჩაწერის ბმულს ეძებდით, დაბრუნდით ფილიალების სიაში.</p></div></div></section></main><PublicFooter /></div>;
}
