import { AnalyticsConsentPreferencesButton, usePublicAnalyticsConsent } from "@/contexts/PublicAnalyticsConsentContext";
import { PublicFooter, PublicHeader } from "@/components/public/PublicPrimitives";
import { usePublicMeta } from "@/components/public/PublicMeta";
import { Button } from "@/components/ui/button";

export default function Privacy() {
  const { choice, setChoice } = usePublicAnalyticsConsent();
  usePublicMeta({ title: "Analytics კონფიდენციალურობა | SalonFlow", description: "SalonFlow-ის consent-based public conversion analytics არჩევანი და მონაცემის მინიმიზაციის პრინციპები.", canonicalPath: "/privacy" });
  return <div className="sf-public-page"><PublicHeader /><main id="main-content" className="sf-salon-section min-h-screen"><div className="sf-public-container max-w-3xl py-12 sm:py-16"><p className="sf-salon-eyebrow">კონფიდენციალურობა</p><h1 className="sf-display mt-4 text-4xl font-semibold leading-tight sm:text-5xl">Public analytics — თქვენი არჩევანით.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[var(--sf-muted)]">SalonFlow-ის public conversion analytics არ იწყება, სანამ თავად არ დაეთანხმებით. უარის შემთხვევაში analytics event საერთოდ არ იგზავნება.</p><section className="mt-8 rounded-[var(--sf-radius-surface)] border border-[var(--sf-line)] bg-[var(--sf-surface-raised)] p-6"><h2 className="text-xl font-bold">რას ვინახავთ თანხმობისას</h2><p className="mt-3 text-sm leading-6 text-[var(--sf-muted)]">მხოლოდ event ტიპს, გვერდის გზას, consent ვერსიას და დროს. ეს ეხმარება მხოლოდ public funnel-ის aggregate ანალიზს, მაგალითად კატალოგის, რუკის, პროფილისა და booking დაწყების გზების შეფასებაში.</p><h2 className="mt-6 text-xl font-bold">რას არ ვინახავთ</h2><p className="mt-3 text-sm leading-6 text-[var(--sf-muted)]">არ ვინახავთ სახელს, ტელეფონს, ელფოსტას, ძიების ტექსტს, booking დეტალს, სალონის/კლიენტის private მონაცემს, IP მისამართს, cookie identifier-ს ან device fingerprint-ს ამ ფუნქციის ფარგლებში.</p></section><section className="mt-5 rounded-[var(--sf-radius-surface)] border border-[var(--sf-line)] bg-[var(--sf-surface-raised)] p-6"><h2 className="text-xl font-bold">თქვენი მიმდინარე არჩევანი</h2><p className="mt-2 text-sm text-[var(--sf-muted)]">{choice === "accepted" ? "Analytics consent: ჩართულია" : choice === "declined" ? "Analytics consent: გამორთულია" : "ჯერ არ გაქვთ გაკეთებული არჩევანი"}</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={() => setChoice("accepted")}>თანხმობა</Button><Button size="sm" variant="outline" onClick={() => setChoice("declined")}>უარის თქმა / გაუქმება</Button><AnalyticsConsentPreferencesButton className="min-h-9 text-sm" /></div></section></div></main><PublicFooter /></div>;
}
