import React, { useEffect } from "react";
import { Link, useRoute } from "wouter";
import { CalendarDays, ChevronRight, ExternalLink, Instagram, MapPin, Phone, Sparkles, UsersRound } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { WorkspaceState } from "@/components/workspace/WorkspacePrimitives";

const money = (tetri: number) => new Intl.NumberFormat("ka-GE", { style: "currency", currency: "GEL" }).format(tetri / 100);

export default function SalonProfile() {
  const [, params] = useRoute("/salon/:slug");
  const slug = params?.slug ?? "";
  const profile = trpc.public.salonProfile.useQuery(slug, { enabled: Boolean(slug) });
  useEffect(() => { if (profile.data) document.title = `${profile.data.salon.name} | SalonFlow`; }, [profile.data]);
  if (profile.isLoading) return <main className="sf-public-page grid min-h-screen place-items-center px-4"><WorkspaceState kind="loading" title="სალონის გვერდი იტვირთება…" /></main>;
  if (profile.isError) return <main className="sf-public-page grid min-h-screen place-items-center px-4"><WorkspaceState kind="error" title="სალონის გვერდი დროებით მიუწვდომელია" description="შეამოწმეთ კავშირი და სცადეთ მოგვიანებით." /></main>;
  if (!profile.data) return <main className="sf-public-page grid min-h-screen place-items-center px-4"><WorkspaceState kind="empty" title="სალონი ვერ მოიძებნა" description="ბმული შეიძლება შეიცვალა ან გვერდი აღარ არის ხელმისაწვდომი." action={<Link href="/book"><Button>სალონების ნახვა</Button></Link>} /></main>;
  const { salon, services, team, feed, gallery } = profile.data;
  const social = salon.socialLinks ?? {};
  return <main className="sf-public-page min-h-screen"><header className="border-b border-border/70 bg-background/75 backdrop-blur"><div className="container flex min-h-18 items-center justify-between gap-3 py-3"><Link href="/" className="flex items-center gap-2 font-semibold"><span className="sf-brand-mark" aria-hidden="true"><i /><i /><i /></span>SalonFlow</Link><Link href="/book"><Button variant="outline" size="sm">ყველა სალონი</Button></Link></div></header>
    <section className="relative overflow-hidden border-b border-border/70"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,rgb(210_72_171_/_0.16),transparent_36%),radial-gradient(circle_at_80%_20%,rgb(139_92_246_/_0.14),transparent_32%)]" />{salon.coverImageUrl ? <img src={salon.coverImageUrl} alt={salon.coverImageAltKa || `${salon.name}-ის cover ფოტო`} className="absolute inset-0 h-full w-full object-cover opacity-30" /> : null}<div className="container relative py-14 sm:py-20"><p className="text-sm font-semibold text-primary">{salon.organizationName}</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">{salon.name}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground">{salon.publicDescription || "სალონის აღწერა მალე დაემატება."}</p><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground">{salon.address ? <span className="inline-flex items-center gap-2"><MapPin className="size-4" />{salon.address}</span> : null}{salon.phone ? <a href={`tel:${salon.phone}`} className="inline-flex items-center gap-2 hover:text-foreground"><Phone className="size-4" />{salon.phone}</a> : null}</div><div className="mt-8 flex flex-wrap gap-3">{salon.bookingEnabled ? <Link href={`/book/${salon.publicSlug}`}><Button size="lg"><CalendarDays className="mr-2 size-4" />ონლაინ ჩაწერა</Button></Link> : null}{social.instagram ? <a href={social.instagram} target="_blank" rel="noreferrer"><Button size="lg" variant="outline"><Instagram className="mr-2 size-4" />Instagram</Button></a> : null}{social.website ? <a href={social.website} target="_blank" rel="noreferrer"><Button size="lg" variant="outline"><ExternalLink className="mr-2 size-4" />ვებგვერდი</Button></a> : null}</div></div></section>
    <div className="container space-y-16 py-12 sm:py-16"><section><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-primary">ფასების ცხრილი</p><h2 className="mt-2 text-3xl font-semibold">მომსახურებები და ფასები</h2></div>{salon.bookingEnabled ? <Link href={`/book/${salon.publicSlug}`} className="hidden sm:inline-flex"><Button variant="outline">დაჯავშნა <ChevronRight className="ml-1 size-4" /></Button></Link> : null}</div><div className="mt-6 overflow-hidden rounded-2xl border"><div className="divide-y">{services.map(service => <article key={service.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{service.nameKa}</p><p className="mt-1 text-sm text-muted-foreground">{service.categoryNameKa}{service.description ? ` · ${service.description}` : ""}</p></div><div className="flex items-center gap-4 text-sm"><span className="text-muted-foreground">{service.durationMinutes} წთ</span><span className="font-semibold">{service.isFromPrice ? "დან " : ""}{money(service.priceTetri)}</span></div></article>)}{!services.length ? <p className="p-5 text-sm text-muted-foreground">საჯარო მომსახურებები ჯერ არ არის დამატებული.</p> : null}</div></div></section>
      <section><p className="text-sm font-semibold text-primary">ჩვენი გუნდი</p><h2 className="mt-2 text-3xl font-semibold">გაიცანით სპეციალისტები</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{team.map(member => <article key={member.id} className="rounded-2xl border bg-card/45 p-5"><div className="flex items-center gap-4">{member.avatarUrl ? <img src={member.avatarUrl} alt={member.avatarAltKa || `${member.name}-ის ავატარი`} className="size-14 rounded-2xl object-cover" loading="lazy" /> : <div className="grid size-14 place-items-center rounded-2xl bg-primary/12 text-primary"><UsersRound className="size-6" /></div>}<div><p className="font-semibold">{member.name}</p><p className="text-sm text-muted-foreground">{member.jobTitle || member.specialty || "სპეციალისტი"}</p></div></div>{member.bio ? <p className="mt-4 text-sm leading-6 text-muted-foreground">{member.bio}</p> : null}</article>)}{!team.length ? <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground sm:col-span-2 lg:col-span-3">საჯარო გუნდის პროფილები ჯერ არ არის დამატებული.</p> : null}</div></section>
      {gallery.length ? <section><p className="text-sm font-semibold text-primary">დადასტურებული შედეგები</p><h2 className="mt-2 text-3xl font-semibold">Before / after</h2><p className="mt-2 text-sm text-muted-foreground">აქ ჩანს მხოლოდ კლიენტის ცალკე თანხმობით საჯაროდ გამოქვეყნებული შედეგები.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{gallery.map(item => <article key={item.id} className="overflow-hidden rounded-2xl border"><div className="grid grid-cols-2">{item.before ? <figure><img src={item.before.mediaUrl} alt={item.before.altTextKa || "მომსახურებამდე შედეგი"} className="aspect-square w-full object-cover" loading="lazy" /><figcaption className="px-3 py-2 text-xs text-muted-foreground">მანამდე</figcaption></figure> : null}{item.after ? <figure><img src={item.after.mediaUrl} alt={item.after.altTextKa || "მომსახურების შემდეგ შედეგი"} className="aspect-square w-full object-cover" loading="lazy" /><figcaption className="px-3 py-2 text-xs text-muted-foreground">შემდეგ</figcaption></figure> : null}</div></article>)}</div></section> : null}
      {feed.length ? <section><p className="text-sm font-semibold text-primary">სალონის დღიური</p><h2 className="mt-2 text-3xl font-semibold">ახალი feed</h2><div className="mt-6 columns-1 gap-4 sm:columns-2 lg:columns-3">{feed.map(post => <article key={post.id} className="mb-4 break-inside-avoid overflow-hidden rounded-2xl border bg-card/45"><img src={post.mediaUrl} alt={post.altTextKa} className="w-full object-cover" loading="lazy" />{post.titleKa || post.captionKa ? <div className="p-4">{post.titleKa ? <h3 className="font-semibold">{post.titleKa}</h3> : null}{post.captionKa ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{post.captionKa}</p> : null}</div> : null}</article>)}</div></section> : null}
      {!feed.length && !gallery.length ? <section className="rounded-2xl border border-dashed p-6 text-center"><Sparkles className="mx-auto size-6 text-primary" /><p className="mt-3 font-semibold">სალონის ვიზუალური ამბები მალე დაემატება.</p><p className="mt-1 text-sm text-muted-foreground">ამ გვერდზე გამოჩნდება მხოლოდ მფლობელის ან მენეჯერის მიერ დამტკიცებული public მასალა.</p></section> : null}
    </div></main>;
}
