import React, { FormEvent, useMemo, useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { formatGelTetri } from "@/lib/presentation";
import { BriefcaseBusiness, CalendarOff, Clock3, MapPin, Pencil, Plus, Trash2, UsersRound } from "lucide-react";
import { toast } from "sonner";

const roleLabel: Record<string, string> = { OWNER: "მფლობელი", MANAGER: "მენეჯერი", RECEPTIONIST: "ადმინისტრატორი", STAFF: "სპეციალისტი" };
const weekdayLabel: Record<string, string> = { "0": "ორშაბათი", "1": "სამშაბათი", "2": "ოთხშაბათი", "3": "ხუთშაბათი", "4": "პარასკევი", "5": "შაბათი", "6": "კვირა" };
const exceptionTypeLabel: Record<string, string> = { VACATION: "შვებულება", SICK_LEAVE: "ავადმყოფობა", CUSTOM_BLOCK: "ინდივიდუალური ბლოკი", BREAK: "შესვენება", EXTENDED_WORKING_TIME: "გაფართოებული საათები", CLOSURE: "დახურვა" };
type ExceptionType = "VACATION" | "SICK_LEAVE" | "CUSTOM_BLOCK";

export default function Staff() {
  const utils = trpc.useUtils();
  const organizations = trpc.organizations.listMine.useQuery();
  const organizationEntry = organizations.data?.[0];
  const organization = organizationEntry?.organization;
  const canManage = ["OWNER", "MANAGER"].includes(organizationEntry?.membership.role ?? "");
  const staff = trpc.staff.list.useQuery({ organizationId: organization?.id ?? "" }, { enabled: Boolean(organization?.id) });
  const locations = trpc.organizations.listLocations.useQuery({ organizationId: organization?.id ?? "" }, { enabled: Boolean(organization?.id) });
  const scheduleInput = { organizationId: organization?.id ?? "" };
  const workingHours = trpc.staff.listWorkingHours.useQuery(scheduleInput, { enabled: Boolean(organization?.id && canManage) });
  const exceptions = trpc.staff.listScheduleExceptions.useQuery(scheduleInput, { enabled: Boolean(organization?.id && canManage) });
  const performanceInput = useMemo(() => { const endsAt = new Date(); const startsAt = new Date(endsAt); startsAt.setUTCDate(startsAt.getUTCDate() - 30); return { organizationId: organization?.id ?? "", startsAt, endsAt }; }, [organization?.id]);
  const performance = trpc.staff.performance.useQuery(performanceInput, { enabled: Boolean(organization?.id && canManage) });
  const hasOwnProfile = Boolean(staff.data?.some(item => item.membership.id === organizationEntry?.membership.id));

  const [profileOpen, setProfileOpen] = useState(false);
  const [displayName, setDisplayName] = useState("");
  const [jobTitle, setJobTitle] = useState("");
  const [selectedLocationIds, setSelectedLocationIds] = useState<string[]>([]);
  const [formError, setFormError] = useState("");
  const [hoursOpen, setHoursOpen] = useState(false);
  const [hoursEditingId, setHoursEditingId] = useState<string>();
  const [hoursProfileId, setHoursProfileId] = useState("");
  const [hoursLocationId, setHoursLocationId] = useState("");
  const [hoursWeekday, setHoursWeekday] = useState("0");
  const [hoursStart, setHoursStart] = useState("09:00");
  const [hoursEnd, setHoursEnd] = useState("18:00");
  const [hoursError, setHoursError] = useState("");
  const [exceptionOpen, setExceptionOpen] = useState(false);
  const [exceptionEditingId, setExceptionEditingId] = useState<string>();
  const [exceptionProfileId, setExceptionProfileId] = useState("");
  const [exceptionLocationId, setExceptionLocationId] = useState("");
  const [exceptionType, setExceptionType] = useState<ExceptionType>("VACATION");
  const [exceptionStartsAt, setExceptionStartsAt] = useState("");
  const [exceptionEndsAt, setExceptionEndsAt] = useState("");
  const [exceptionReason, setExceptionReason] = useState("");
  const [exceptionError, setExceptionError] = useState("");

  const refreshSchedules = async () => { await Promise.all([workingHours.refetch(), exceptions.refetch()]); };
  const createProfile = trpc.staff.createProfile.useMutation({ onSuccess: async () => { await utils.staff.list.invalidate(); setProfileOpen(false); setDisplayName(""); setJobTitle(""); setSelectedLocationIds([]); } });
  const addWorkingHours = trpc.staff.addWorkingHours.useMutation({ onSuccess: async () => { await refreshSchedules(); toast.success("სამუშაო საათები დაემატა."); setHoursOpen(false); } });
  const updateWorkingHours = trpc.staff.updateWorkingHours.useMutation({ onSuccess: async () => { await refreshSchedules(); toast.success("სამუშაო საათები განახლდა."); setHoursOpen(false); } });
  const deleteWorkingHours = trpc.staff.deleteWorkingHours.useMutation({ onSuccess: async () => { await workingHours.refetch(); toast.success("სამუშაო საათების წესი წაიშალა."); } });
  const addScheduleException = trpc.staff.addScheduleException.useMutation({ onSuccess: async () => { await refreshSchedules(); toast.success("კალენდრის გამონაკლისი დაემატა."); setExceptionOpen(false); } });
  const updateScheduleException = trpc.staff.updateScheduleException.useMutation({ onSuccess: async () => { await refreshSchedules(); toast.success("კალენდრის გამონაკლისი განახლდა."); setExceptionOpen(false); } });
  const deleteException = trpc.staff.deleteScheduleException.useMutation({ onSuccess: async () => { await exceptions.refetch(); toast.success("კალენდრის გამონაკლისი წაიშალა."); } });

  const openHoursCreate = (staffProfileId: string) => { setHoursEditingId(undefined); setHoursProfileId(staffProfileId); setHoursLocationId(""); setHoursWeekday("0"); setHoursStart("09:00"); setHoursEnd("18:00"); setHoursError(""); setHoursOpen(true); };
  const openHoursEdit = (item: NonNullable<typeof workingHours.data>[number]) => { setHoursEditingId(item.rule.id); setHoursProfileId(item.rule.staffProfileId); setHoursLocationId(item.rule.locationId); setHoursWeekday(String(item.rule.weekday)); setHoursStart(item.rule.startLocalTime.slice(0, 5)); setHoursEnd(item.rule.endLocalTime.slice(0, 5)); setHoursError(""); setHoursOpen(true); };
  const openExceptionCreate = () => { setExceptionEditingId(undefined); setExceptionProfileId(""); setExceptionLocationId(""); setExceptionType("VACATION"); setExceptionStartsAt(""); setExceptionEndsAt(""); setExceptionReason(""); setExceptionError(""); setExceptionOpen(true); };
  const openExceptionEdit = (item: NonNullable<typeof exceptions.data>[number]) => { setExceptionEditingId(item.exception.id); setExceptionProfileId(item.exception.staffProfileId ?? ""); setExceptionLocationId(item.exception.locationId ?? ""); setExceptionType(item.exception.type as ExceptionType); setExceptionStartsAt(toDateTimeLocal(item.exception.startsAt)); setExceptionEndsAt(toDateTimeLocal(item.exception.endsAt)); setExceptionReason(item.exception.reason ?? ""); setExceptionError(""); setExceptionOpen(true); };
  const submitProfile = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!organization || !organizationEntry || !selectedLocationIds.length) { setFormError("აირჩიეთ მინიმუმ ერთი აქტიური ფილიალი."); return; } createProfile.mutate({ organizationId: organization.id, membershipId: organizationEntry.membership.id, publicDisplayName: displayName, jobTitle: jobTitle || undefined, onlineBookingVisible: true, color: "#17826A", locationIds: selectedLocationIds }); };
  const submitHours = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!organization || !hoursProfileId || !hoursLocationId || hoursStart >= hoursEnd) { setHoursError("შეამოწმეთ სპეციალისტი, ფილიალი და დროის დიაპაზონი."); return; } const input = { organizationId: organization.id, staffProfileId: hoursProfileId, locationId: hoursLocationId, weekday: Number(hoursWeekday), startLocalTime: hoursStart, endLocalTime: hoursEnd }; if (hoursEditingId) updateWorkingHours.mutate({ ...input, id: hoursEditingId }); else addWorkingHours.mutate(input); };
  const submitException = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!organization || !exceptionProfileId || !exceptionLocationId || !exceptionStartsAt || !exceptionEndsAt) { setExceptionError("აირჩიეთ სპეციალისტი, ფილიალი და დროის დიაპაზონი."); return; } const startsAt = new Date(exceptionStartsAt); const endsAt = new Date(exceptionEndsAt); if (Number.isNaN(startsAt.getTime()) || Number.isNaN(endsAt.getTime()) || startsAt >= endsAt) { setExceptionError("დასრულება დაწყებაზე გვიან უნდა იყოს."); return; } const input = { organizationId: organization.id, staffProfileId: exceptionProfileId, locationId: exceptionLocationId, type: exceptionType, startsAt, endsAt, fullDay: false, reason: exceptionReason || undefined }; if (exceptionEditingId) updateScheduleException.mutate({ ...input, id: exceptionEditingId }); else addScheduleException.mutate(input); };

  return <DashboardLayout><div className="mx-auto min-w-0 w-full max-w-7xl space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0"><p className="text-sm font-medium text-primary">გუნდის სამუშაო სივრცე</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">გუნდი</h1><p className="mt-2 text-sm text-muted-foreground">სპეციალისტების როლები, საჯარო პროფილები და ფილიალების აქტიური ქსელი.</p></div><div className="flex flex-wrap gap-2"><Badge variant="outline" className="border-primary/30 bg-primary/5 px-3 py-1 text-primary">{organization?.name ?? "სამუშაო სივრცე"}</Badge>{organization && canManage && staff.data?.length ? <Button variant="outline" onClick={openExceptionCreate}>კალენდრის ბლოკი</Button> : null}{organization && canManage && !hasOwnProfile ? <Button onClick={() => setProfileOpen(true)}><Plus className="mr-2 h-4 w-4" />ჩემი პროფილის დამატება</Button> : null}</div></header>
    {organizations.isLoading ? <StateCard text="გუნდის სამუშაო სივრცე იტვირთება…" /> : null}{organizations.isError ? <StateCard error text="სამუშაო სივრცის მონაცემები დროებით მიუწვდომელია." /> : null}{!organizations.isLoading && !organizations.isError && !organization ? <StateCard text="გუნდის გვერდის სანახავად ჯერ შექმენით სამუშაო სივრცე." /> : null}
    {organization ? <><div className="grid gap-4 lg:grid-cols-3"><Metric icon={UsersRound} label="აქტიური პროფილები" value={staff.isLoading ? "…" : String(staff.data?.length ?? 0)} hint="ორგანიზაციის აქტიური თანამშრომლები" /><Metric icon={MapPin} label="აქტიური ფილიალები" value={locations.isLoading ? "…" : String(locations.data?.length ?? 0)} hint="ფილიალები, სადაც გუნდი განთავსდება" /><Metric icon={BriefcaseBusiness} label="ონლაინ პროფილები" value={staff.isLoading ? "…" : String(staff.data?.filter(item => item.profile.onlineBookingVisible).length ?? 0)} hint="საჯარო ჩაწერაში ხილული სპეციალისტები" /></div>
      <Card><CardHeader><CardTitle>აქტიური გუნდი</CardTitle></CardHeader><CardContent><div className="grid gap-4 lg:grid-cols-2">{staff.isLoading ? <p className="text-sm text-muted-foreground">გუნდის პროფილები იტვირთება…</p> : null}{!staff.isLoading && !staff.data?.length ? <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">პირველი სპეციალისტის პროფილი ჯერ არ არის დამატებული.</p> : null}{staff.data?.map(item => <div key={item.profile.id} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{item.profile.publicDisplayName}</h2><p className="mt-1 text-sm text-muted-foreground">{item.profile.jobTitle || item.profile.specialty || "როლი და სპეციალიზაცია დაემატება აქ"}</p></div><Badge variant="outline">{roleLabel[item.membership.role] ?? item.membership.role}</Badge></div><p className="mt-4 text-sm text-muted-foreground">საჯარო პროფილი: {item.profile.onlineBookingVisible ? "აქტიურია" : "დამალულია"}</p>{canManage ? <Button variant="outline" size="sm" className="mt-4" onClick={() => openHoursCreate(item.profile.id)}>სამუშაო საათები</Button> : null}</div>)}</div></CardContent></Card>
      {canManage ? <><StaffPerformancePanel isLoading={performance.isLoading} isError={performance.isError} data={performance.data} /><Card><CardHeader><CardTitle>განრიგის წესები და ბლოკები</CardTitle></CardHeader><CardContent className="grid gap-5 lg:grid-cols-2"><ScheduleRules data={workingHours.data} onEdit={openHoursEdit} onDelete={id => organization && deleteWorkingHours.mutate({ organizationId: organization.id, id })} /><ScheduleExceptions data={exceptions.data} onEdit={openExceptionEdit} onDelete={id => organization && deleteException.mutate({ organizationId: organization.id, id })} /></CardContent></Card></> : null}
    </> : null}
  </div><ProfileDialog open={profileOpen} setOpen={setProfileOpen} submit={submitProfile} displayName={displayName} setDisplayName={setDisplayName} jobTitle={jobTitle} setJobTitle={setJobTitle} locations={locations.data ?? []} selected={selectedLocationIds} setSelected={setSelectedLocationIds} error={formError} pending={createProfile.isPending} /><HoursDialog open={hoursOpen} setOpen={setHoursOpen} editing={Boolean(hoursEditingId)} locations={locations.data ?? []} locationId={hoursLocationId} setLocationId={setHoursLocationId} weekday={hoursWeekday} setWeekday={setHoursWeekday} start={hoursStart} setStart={setHoursStart} end={hoursEnd} setEnd={setHoursEnd} submit={submitHours} error={hoursError} pending={addWorkingHours.isPending || updateWorkingHours.isPending} /><ExceptionDialog open={exceptionOpen} setOpen={setExceptionOpen} editing={Boolean(exceptionEditingId)} staff={staff.data ?? []} locations={locations.data ?? []} profileId={exceptionProfileId} setProfileId={setExceptionProfileId} locationId={exceptionLocationId} setLocationId={setExceptionLocationId} type={exceptionType} setType={setExceptionType} starts={exceptionStartsAt} setStarts={setExceptionStartsAt} ends={exceptionEndsAt} setEnds={setExceptionEndsAt} reason={exceptionReason} setReason={setExceptionReason} submit={submitException} error={exceptionError} pending={addScheduleException.isPending || updateScheduleException.isPending} /></DashboardLayout>;
}

function ScheduleRules({ data, onEdit, onDelete }: { data: any[] | undefined; onEdit: (item: any) => void; onDelete: (id: string) => void }) { return <section><div className="mb-3 flex items-center gap-2"><Clock3 className="h-4 w-4 text-primary" /><p className="text-sm font-medium">სამუშაო საათები</p></div>{!data?.length ? <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">სამუშაო საათების წესი ჯერ არ არის დამატებული.</p> : <div className="space-y-2">{data.map(item => <div key={item.rule.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-medium">{item.profile.publicDisplayName} · {weekdayLabel[String(item.rule.weekday)]}</p><p className="text-sm text-muted-foreground">{item.location.name} · {item.rule.startLocalTime}–{item.rule.endLocalTime}</p></div><div className="flex"><Button variant="ghost" size="icon" aria-label="სამუშაო საათების შეცვლა" onClick={() => onEdit(item)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label="სამუშაო საათების წაშლა" onClick={() => onDelete(item.rule.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div>)}</div>}</section>; }
function ScheduleExceptions({ data, onEdit, onDelete }: { data: any[] | undefined; onEdit: (item: any) => void; onDelete: (id: string) => void }) { return <section><div className="mb-3 flex items-center gap-2"><CalendarOff className="h-4 w-4 text-primary" /><p className="text-sm font-medium">კალენდრის გამონაკლისები</p></div>{!data?.length ? <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">კალენდრის გამონაკლისი ჯერ არ არის დამატებული.</p> : <div className="space-y-2">{data.map(item => <div key={item.exception.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-medium">{item.profile?.publicDisplayName ?? item.location?.name ?? "ორგანიზაციის ბლოკი"}</p><p className="text-sm text-muted-foreground">{exceptionTypeLabel[item.exception.type]} · {formatScheduleDate(item.exception.startsAt)}–{formatScheduleDate(item.exception.endsAt)}</p></div><div className="flex"><Button variant="ghost" size="icon" aria-label="კალენდრის ბლოკის შეცვლა" onClick={() => onEdit(item)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label="კალენდრის ბლოკის წაშლა" onClick={() => onDelete(item.exception.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div>)}</div>}</section>; }
export function StaffPerformancePanel({ isLoading, isError, data }: { isLoading: boolean; isError: boolean; data?: Array<{ profile: { id: string; publicDisplayName: string }; metrics: { completedAppointments: number; serviceVolume: number; bookedRevenueTetri: number } }> }) { return <Card><CardHeader><CardTitle>ბოლო 30 დღის სპეციალისტების სიგნალები</CardTitle></CardHeader><CardContent>{isLoading ? <p className="text-sm text-muted-foreground">მონაცემები იტვირთება…</p> : null}{isError ? <p className="text-sm text-destructive">სპეციალისტების მაჩვენებლები ვერ ჩაიტვირთა.</p> : null}{!isLoading && !isError ? <div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-3">{data?.map(item => <div key={item.profile.id} className="rounded-xl border bg-muted/15 p-4"><p className="font-medium">{item.profile.publicDisplayName}</p><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Signal label="დასრულებული" value={String(item.metrics.completedAppointments)} /><Signal label="მომსახურება" value={String(item.metrics.serviceVolume)} /><Signal label="ჯავშნები" value={formatGEL(item.metrics.bookedRevenueTetri)} /></div></div>)}{!data?.length ? <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">არჩეულ პერიოდში სპეციალისტის მონაცემი ჯერ არ არის.</p> : null}</div> : null}</CardContent></Card>; }
function ProfileDialog({ open, setOpen, submit, displayName, setDisplayName, jobTitle, setJobTitle, locations, selected, setSelected, error, pending }: any) { const toggle = (id: string) => setSelected((current: string[]) => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); return <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>ჩემი სპეციალისტის პროფილი</DialogTitle><DialogDescription>პროფილი უკავშირდება თქვენს მიმდინარე წევრობას.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><Field label="საჯარო სახელი"><Input value={displayName} onChange={event => setDisplayName(event.target.value)} minLength={2} required /></Field><Field label="როლი ან სპეციალიზაცია"><Input value={jobTitle} onChange={event => setJobTitle(event.target.value)} /></Field><fieldset className="space-y-2"><legend className="text-sm font-medium">ფილიალები</legend>{locations.map((location: any) => <label key={location.id} className="flex items-center gap-2 rounded-lg border p-2"><input type="checkbox" checked={selected.includes(location.id)} onChange={() => toggle(location.id)} />{location.name}</label>)}</fieldset>{error ? <p className="text-sm text-destructive">{error}</p> : null}<DialogFooter><Button type="submit" disabled={pending}>{pending ? "ინახება…" : "პროფილის შენახვა"}</Button></DialogFooter></form></DialogContent></Dialog>; }
function HoursDialog({ open, setOpen, editing, locations, locationId, setLocationId, weekday, setWeekday, start, setStart, end, setEnd, submit, error, pending }: any) { return <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "სამუშაო საათების შეცვლა" : "სამუშაო საათების დამატება"}</DialogTitle><DialogDescription>ცვლილება მოქმედებს მხოლოდ აქტიურ ფილიალში მინიჭებულ სპეციალისტზე.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><Field label="ფილიალი"><Select value={locationId} onValueChange={setLocationId}><SelectTrigger><SelectValue placeholder="აირჩიეთ ფილიალი" /></SelectTrigger><SelectContent>{locations.map((location: any) => <SelectItem key={location.id} value={location.id}>{location.name}</SelectItem>)}</SelectContent></Select></Field><Field label="დღე"><Select value={weekday} onValueChange={setWeekday}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(weekdayLabel).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="დაწყება"><Input type="time" value={start} onChange={event => setStart(event.target.value)} required /></Field><Field label="დასრულება"><Input type="time" value={end} onChange={event => setEnd(event.target.value)} required /></Field></div>{error ? <p className="text-sm text-destructive">{error}</p> : null}<DialogFooter><Button type="submit" disabled={pending}>{pending ? "ინახება…" : editing ? "ცვლილების შენახვა" : "საათების შენახვა"}</Button></DialogFooter></form></DialogContent></Dialog>; }
function ExceptionDialog({ open, setOpen, editing, staff, locations, profileId, setProfileId, locationId, setLocationId, type, setType, starts, setStarts, ends, setEnds, reason, setReason, submit, error, pending }: any) { return <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "კალენდრის ბლოკის შეცვლა" : "კალენდრის გამონაკლისი"}</DialogTitle><DialogDescription>შვებულება, ავადმყოფობა ან ინდივიდუალური სამუშაო ბლოკი.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="სპეციალისტი"><Select value={profileId} onValueChange={setProfileId}><SelectTrigger><SelectValue placeholder="აირჩიეთ სპეციალისტი" /></SelectTrigger><SelectContent>{staff.map((item: any) => <SelectItem key={item.profile.id} value={item.profile.id}>{item.profile.publicDisplayName}</SelectItem>)}</SelectContent></Select></Field><Field label="ფილიალი"><Select value={locationId} onValueChange={setLocationId}><SelectTrigger><SelectValue placeholder="აირჩიეთ ფილიალი" /></SelectTrigger><SelectContent>{locations.map((location: any) => <SelectItem key={location.id} value={location.id}>{location.name}</SelectItem>)}</SelectContent></Select></Field></div><Field label="ტიპი"><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="VACATION">შვებულება</SelectItem><SelectItem value="SICK_LEAVE">ავადმყოფობა</SelectItem><SelectItem value="CUSTOM_BLOCK">ინდივიდუალური ბლოკი</SelectItem></SelectContent></Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="დაწყება"><Input type="datetime-local" value={starts} onChange={event => setStarts(event.target.value)} required /></Field><Field label="დასრულება"><Input type="datetime-local" value={ends} onChange={event => setEnds(event.target.value)} required /></Field></div><Field label="მიზეზი"><Input value={reason} onChange={event => setReason(event.target.value)} /></Field>{error ? <p className="text-sm text-destructive">{error}</p> : null}<DialogFooter><Button type="submit" disabled={pending}>{pending ? "ინახება…" : editing ? "ცვლილების შენახვა" : "გამონაკლისის შენახვა"}</Button></DialogFooter></form></DialogContent></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function Metric({ icon: Icon, label, value, hint }: { icon: typeof UsersRound; label: string; value: string; hint: string }) { return <Card><CardContent className="p-5"><Icon className="h-5 w-5 text-primary" /><p className="mt-4 text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-3 text-xs text-muted-foreground">{hint}</p></CardContent></Card>; }
function StateCard({ text, error = false }: { text: string; error?: boolean }) { return <Card className={error ? "border-destructive/30 bg-destructive/5" : ""}><CardContent className={`p-8 text-sm ${error ? "text-destructive" : "text-muted-foreground"}`}>{text}</CardContent></Card>; }
function Signal({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] leading-3 text-muted-foreground">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>; }
function formatGEL(tetri: number) { return formatGelTetri(tetri); }
function formatScheduleDate(value: Date) { return new Intl.DateTimeFormat("ka-GE", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
function toDateTimeLocal(value: Date) { const date = new Date(value); const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60_000).toISOString().slice(0, 16); }
