import React, { type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Check, ChevronRight, Clock3, PencilLine, Sparkles } from "lucide-react";

export type BookingSummaryRow = { label: string; value: string; ready: boolean; editStep?: number };
export type BookingSlot = { startsAt: string; label: string };

export function BookingStepHeader({ step, eyebrow, title, description, children }: { step: number; eyebrow?: string; title: string; description: string; children?: ReactNode }) {
  return <CardHeader className="pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--sf-accent-strong)]">{eyebrow ?? `ნაბიჯი ${String(step).padStart(2, "0")}`}</p><CardTitle className="mt-2 text-xl">{title}</CardTitle><p className="mt-1 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div>{children}</div></CardHeader>;
}

export function BookingChoiceCard({ selected, onSelect, children, tone = "brand", label, conversionEvent }: { selected: boolean; onSelect: () => void; children: ReactNode; tone?: "brand" | "availability"; label: string; conversionEvent?: string }) {
  const selectedClass = tone === "availability" ? "border-[var(--sf-jade)] bg-[var(--sf-jade)]/7" : "border-[var(--sf-accent-strong)] bg-[var(--sf-accent-strong)]/5";
  const accent = tone === "availability" ? "bg-[var(--sf-jade)]" : "bg-[var(--sf-accent-strong)]";
  return <button type="button" data-conversion-event={conversionEvent} aria-label={label} aria-pressed={selected} onClick={onSelect} className={`sf-booking-choice relative w-full rounded-2xl border p-4 text-left shadow-sm transition-[transform,box-shadow,border-color,background-color] duration-200 motion-reduce:transition-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--sf-accent-strong)] focus-visible:ring-offset-2 ${selected ? selectedClass : "border-[var(--sf-ink)]/10 bg-white hover:-translate-y-0.5 hover:border-[var(--sf-accent-strong)]/55 hover:shadow-md motion-reduce:hover:translate-y-0"}`}><span className={`absolute right-4 top-4 inline-flex size-6 items-center justify-center rounded-full text-white transition-opacity ${selected ? `${accent} opacity-100` : "bg-[var(--sf-ink)]/10 opacity-0"}`} aria-hidden="true"><Check className="size-3.5" /></span>{children}</button>;
}

export function BookingVisitSummary({ rows, onEdit, title = "თქვენი ვიზიტი", description = "არჩევანი განახლდება თითოეულ ნაბიჯზე." }: { rows: BookingSummaryRow[]; onEdit?: (step: number) => void; title?: string; description?: string }) {
  return <Card className="border-[var(--sf-ink)]/10 bg-white shadow-sm"><CardHeader className="pb-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[var(--sf-accent-strong)]/10 text-[var(--sf-accent-strong)]"><Sparkles className="size-5" aria-hidden="true" /></span><div><CardTitle className="text-lg">{title}</CardTitle><p className="mt-0.5 text-xs leading-5 text-muted-foreground">{description}</p></div></div></CardHeader><CardContent className="space-y-2.5">{rows.map(row => { const editStep = row.editStep; return <div key={row.label} className={`group rounded-xl border p-3 ${row.ready ? "border-[var(--sf-ink)]/8 bg-[var(--sf-surface-hover)]/65" : "border-dashed border-[var(--sf-line)] bg-[var(--sf-surface-subtle)]/70"}`}><div className="flex gap-2"><div className="min-w-0 flex-1"><p className="text-[0.68rem] font-semibold uppercase tracking-[0.14em] text-[var(--sf-muted)]">{row.label}</p><p className={`mt-1 text-sm leading-5 ${row.ready ? "font-medium text-[var(--sf-ink)]" : "text-[var(--sf-muted)]"}`}>{row.value}</p></div>{row.ready && editStep !== undefined && onEdit ? <Button type="button" variant="ghost" size="icon" className="size-10 shrink-0" aria-label={`${row.label} შეცვლა`} onClick={() => onEdit(editStep)}><PencilLine className="size-4" aria-hidden="true" /></Button> : null}</div></div>; })}</CardContent></Card>;
}

export function BookingSlotGroup({ title, slots, selectedStartsAt, onSelect, conversionEvent }: { title: string; slots: BookingSlot[]; selectedStartsAt: string; onSelect: (startsAt: string) => void; conversionEvent?: string }) {
  if (!slots.length) return null;
  return <section aria-label={`${title} საათები`}><div className="mb-2 flex items-center gap-2"><Clock3 className="size-4 text-[var(--sf-accent-strong)]" aria-hidden="true" /><h3 className="text-sm font-semibold">{title}</h3></div><div className="grid grid-cols-3 gap-2 sm:grid-cols-4">{slots.map(slot => { const active = selectedStartsAt === slot.startsAt; return <button key={slot.startsAt} type="button" data-conversion-event={conversionEvent} aria-pressed={active} onClick={() => onSelect(slot.startsAt)} className={`sf-interactive min-h-11 rounded-xl border px-2 py-2.5 text-sm font-semibold tabular-nums focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--sf-accent-strong)] focus-visible:ring-offset-2 ${active ? "border-transparent text-white shadow-[var(--sf-glow-brand)] [background-image:var(--sf-gradient-brand)]" : "border-[var(--sf-line)] bg-[var(--sf-surface)] text-[var(--sf-ink)] hover:border-[color-mix(in_srgb,var(--sf-accent-strong)_45%,var(--sf-line))] hover:text-[var(--sf-accent-strong)]"}`}>{slot.label}</button>; })}</div></section>;
}

export function BookingMobileAction({ step, label, detail, disabled, onContinue }: { step: number; label: string; detail: string; disabled: boolean; onContinue: () => void }) {
  return <div className="fixed inset-x-0 bottom-0 z-30 border-t border-border/90 bg-background/95 px-4 pb-[max(1rem,env(safe-area-inset-bottom))] pt-3 shadow-[0_-12px_30px_rgb(0_0_0_/_0.16)] backdrop-blur lg:hidden"><div className="mx-auto flex max-w-xl items-center gap-3"><div className="min-w-0 flex-1"><p className="text-[0.68rem] font-semibold uppercase tracking-[0.12em] text-muted-foreground">ნაბიჯი {step + 1} / 4</p><p className="truncate text-xs font-medium text-foreground">{detail}</p></div><Button className="min-h-11 shrink-0" disabled={disabled} onClick={onContinue}>{label}<ChevronRight className="ml-1 size-4" aria-hidden="true" /></Button></div></div>;
}
