import React, { useMemo, useState } from "react";
import { Calendar } from "@/components/ui/calendar";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { CalendarDays, Check, Clock3, X } from "lucide-react";
import { ka } from "date-fns/locale";
import { dateKeyInTimeZone, isDateKeyInPast, isLocalDateTimeElapsed } from "@shared/timezones";

const MONTH_FORMATTER = new Intl.DateTimeFormat("ka-GE", { month: "long", year: "numeric", timeZone: "Asia/Tbilisi" });
const DATE_FORMATTER = new Intl.DateTimeFormat("ka-GE", { weekday: "long", day: "numeric", month: "long", timeZone: "Asia/Tbilisi" });

function dateForPicker(dateKey: string) { return new Date(`${dateKey}T12:00:00.000Z`); }
function dateKeyForPicker(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; }
function dateLabel(dateKey: string) { return DATE_FORMATTER.format(dateForPicker(dateKey)); }

export function GeorgianDatePicker({ value, onChange, timeZone = "Asia/Tbilisi", disabled = false, minDateKey, maxDateKey }: { value: string; onChange: (dateKey: string) => void; timeZone?: string; disabled?: boolean; minDateKey?: string; maxDateKey?: string }) {
  const [open, setOpen] = useState(false);
  const todayKey = dateKeyInTimeZone(new Date(), timeZone);
  const selected = value ? dateForPicker(value) : undefined;
  const outsideBoundary = (dateKey: string) => isDateKeyInPast(dateKey, timeZone) || Boolean(minDateKey && dateKey < minDateKey) || Boolean(maxDateKey && dateKey > maxDateKey);
  return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button type="button" variant="outline" disabled={disabled} className="min-h-11 w-full justify-between border-[var(--sf-line)] bg-white px-3 text-left font-medium hover:bg-[var(--sf-surface-hover)]" aria-label="სასურველი თარიღის არჩევა"><span className="flex min-w-0 items-center gap-2"><CalendarDays className="size-4 shrink-0 text-[var(--sf-accent-strong)]" aria-hidden="true" /><span className="truncate">{value ? dateLabel(value) : "აირჩიეთ თარიღი"}</span></span><span className="rounded-full bg-[var(--sf-surface-subtle)] px-2 py-1 text-[0.68rem] font-semibold text-[var(--sf-muted)]">ქართული კალენდარი</span></Button></PopoverTrigger><PopoverContent align="start" className="w-auto rounded-2xl border-[var(--sf-line)] bg-white p-2 shadow-xl"><div className="px-2 pb-1 pt-2"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--sf-accent-strong)]">სასურველი თარიღი</p><p className="mt-1 text-xs leading-5 text-muted-foreground">წარსული დღეები მიუწვდომელია.</p></div><Calendar mode="single" locale={ka} selected={selected} onSelect={date => { if (!date) return; const next = dateKeyForPicker(date); if (outsideBoundary(next)) return; onChange(next); setOpen(false); }} disabled={date => outsideBoundary(dateKeyForPicker(date))} initialFocus defaultMonth={selected ?? dateForPicker(todayKey)} formatters={{ formatCaption: date => MONTH_FORMATTER.format(date), formatWeekdayName: date => new Intl.DateTimeFormat("ka-GE", { weekday: "short" }).format(date) }} classNames={{ day_button: "min-h-10 min-w-10 rounded-xl", disabled: "cursor-not-allowed opacity-35 line-through", today: "border border-[var(--sf-accent-strong)]/40 bg-[var(--sf-accent-strong)]/8" }} /></PopoverContent></Popover>;
}

export function GeorgianTimePicker({ dateKey, value, onChange, timeZone = "Asia/Tbilisi", disabled = false, optional = true, startHour = 8, endHour = 21 }: { dateKey: string; value: string; onChange: (timeKey: string) => void; timeZone?: string; disabled?: boolean; optional?: boolean; startHour?: number; endHour?: number }) {
  const [open, setOpen] = useState(false);
  const times = useMemo(() => Array.from({ length: (endHour - startHour) * 2 }, (_, index) => `${String(startHour + Math.floor(index / 2)).padStart(2, "0")}:${index % 2 ? "30" : "00"}`), [startHour, endHour]);
  const isElapsed = (time: string) => Boolean(dateKey) && isLocalDateTimeElapsed(dateKey, time, timeZone);
  return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button type="button" variant="outline" disabled={disabled || !dateKey} className="min-h-11 w-full justify-between border-[var(--sf-line)] bg-white px-3 text-left font-medium hover:bg-[var(--sf-surface-hover)]" aria-label="სასურველი საათის არჩევა"><span className="flex min-w-0 items-center gap-2"><Clock3 className="size-4 shrink-0 text-[var(--sf-accent-strong)]" aria-hidden="true" /><span className="truncate">{value || (dateKey ? "ზუსტი დრო არ არის მითითებული" : "ჯერ აირჩიეთ თარიღი")}</span></span><span className="text-xs text-[var(--sf-muted)]">{value ? "შეცვლა" : "არჩევა"}</span></Button></PopoverTrigger><PopoverContent align="start" className="w-[min(20rem,calc(100vw-2rem))] rounded-2xl border-[var(--sf-line)] bg-white p-3 shadow-xl"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--sf-accent-strong)]">სასურველი დრო</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{dateKey === dateKeyInTimeZone(new Date(), timeZone) ? "დღის გასული საათები მიუწვდომელია." : "აირჩიეთ სურვილისამებრ."}</p></div>{optional && value ? <Button type="button" variant="ghost" size="sm" className="min-h-9" onClick={() => { onChange(""); setOpen(false); }}><X className="mr-1 size-3.5" aria-hidden="true" />გასუფთავება</Button> : null}</div><div className="mt-3 grid grid-cols-4 gap-2" role="listbox" aria-label="სასურველი საათი">{times.map(time => { const selected = value === time; const elapsed = isElapsed(time); return <button key={time} type="button" role="option" aria-selected={selected} disabled={elapsed} onClick={() => { onChange(time); setOpen(false); }} className={`min-h-11 rounded-xl border text-sm font-semibold tabular-nums transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--sf-focus)] ${selected ? "border-transparent text-white [background-image:var(--sf-gradient-brand)]" : elapsed ? "cursor-not-allowed border-transparent bg-[var(--sf-surface-subtle)] text-[var(--sf-muted)]/45 line-through" : "border-[var(--sf-line)] bg-white hover:border-[var(--sf-accent-strong)] hover:text-[var(--sf-accent-strong)]"}`}>{selected ? <span className="inline-flex items-center gap-1"><Check className="size-3.5" aria-hidden="true" />{time}</span> : time}</button>; })}</div>{optional ? <p className="mt-3 rounded-xl bg-[var(--sf-surface-subtle)] px-3 py-2 text-xs leading-5 text-muted-foreground">ზუსტი დრო არასავალდებულოა; სალონი თქვენს მოთხოვნას ხელმისაწვდომობის მიხედვით განიხილავს.</p> : null}</PopoverContent></Popover>;
}
